'use client';

import { Fragment, useMemo } from 'react';

import type { SectionProps } from '@/lib/types';
import { formatEntityName } from '@/lib/format';
import {
  buildCashFlow,
  cashFlowRecords,
  type CfActivityRow,
} from '@/lib/performance/cashFlow/model';
import { PageTitle } from '@/components/layout/PageTitle';
import { KpiCard } from '@/components/dashboard/kpi/KpiCard';
import { WaterfallChart } from '@/components/dashboard/viz/WaterfallChart';
import { CompositionDonut } from '@/components/dashboard/viz/CompositionDonut';
import { TrendChart } from '@/components/dashboard/viz/TrendChart';

const currencyFormatter = new Intl.NumberFormat('fr-FR', {
  style: 'currency',
  currency: 'EUR',
  maximumFractionDigits: 0,
});

const compactCurrency = new Intl.NumberFormat('fr-FR', {
  style: 'currency',
  currency: 'EUR',
  notation: 'compact',
  maximumFractionDigits: 1,
});

const PAGE_HINT =
  'How cash moved over the selected period: what operations generated, what was invested, and how the balance was financed.';

function formatAmount(value: number): string {
  return currencyFormatter.format(value);
}

function amountClassName(value: number): string {
  return value < 0 ? 'text-red-500' : 'text-[var(--text)]';
}

export function CashFlowSection({ company, site, datasets }: SectionProps) {
  const records = useMemo(
    () => cashFlowRecords(datasets.cash_flow),
    [datasets.cash_flow],
  );
  const statement = useMemo(() => buildCashFlow(records), [records]);

  const perimeterSuffix = company
    ? ` — ${formatEntityName(company.display_name)}`
    : site
      ? ` — ${formatEntityName(site.name)}`
      : '';

  const { kpis, periods } = statement;

  if (records.length === 0) {
    return (
      <div className="fade-in">
        <div className="mb-8">
          <PageTitle hint={PAGE_HINT}>Cash Flow{perimeterSuffix}</PageTitle>
        </div>
        <div className="glass rounded-lg p-6">
          <p className="text-sm text-[var(--text-muted)]">
            No cash flow data for this perimeter.
          </p>
        </div>
      </div>
    );
  }

  const firstLabel = periods[0]?.label ?? '—';
  const lastLabel = periods[periods.length - 1]?.label ?? '—';
  const rangeLabel =
    periods.length > 1 ? `${firstLabel} → ${lastLabel}` : firstLabel;

  return (
    <div className="fade-in">
      <div className="mb-8">
        <PageTitle hint={PAGE_HINT}>Cash Flow{perimeterSuffix}</PageTitle>
        <p className="mt-2 text-sm text-[var(--text-muted)]">
          {rangeLabel}
          {statement.isReconciled ? ' · Opening + movements = Closing' : ''}
        </p>
      </div>

      {/* ---- KPI cards ---------------------------------------------------- */}
      <div className="mb-8 grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-3">
        <KpiCard
          label="Operating Cash Flow"
          value={kpis.operating}
          valueStyle="currency"
          tone={kpis.operating >= 0 ? 'success' : 'danger'}
          subtitle="Cash generated by the business"
          hint="Cash from day-to-day operations, before investment and financing."
        />
        <KpiCard
          label="Investing Cash Flow"
          value={kpis.investing}
          valueStyle="currency"
          tone={kpis.investing >= 0 ? 'success' : 'orange'}
          subtitle="Capex, disposals and financial investments"
          hint="Cash spent on (or released by) long-term assets. Normally negative for a growing business."
        />
        <KpiCard
          label="Financing Cash Flow"
          value={kpis.financing}
          valueStyle="currency"
          tone={kpis.financing >= 0 ? 'success' : 'orange'}
          subtitle="Borrowings, equity and dividends"
          hint="Cash raised from or returned to lenders and shareholders."
        />
        <KpiCard
          label="Free Cash Flow"
          value={kpis.freeCashFlow}
          valueStyle="currency"
          tone={kpis.freeCashFlow >= 0 ? 'success' : 'danger'}
          subtitle="Operating cash flow − capital expenditure"
          hint="Cash left after maintaining and growing the asset base."
        />
        <KpiCard
          label="Ending Cash"
          value={kpis.endingCash}
          valueStyle="currency"
          subtitle={`Opening ${compactCurrency.format(
            kpis.openingCash,
          )} · Net ${compactCurrency.format(kpis.netChange)}`}
          hint="Cash and equivalents at the end of the selected period."
        />
        <KpiCard
          label="Cash Conversion"
          value={kpis.cashConversion ?? 0}
          valueStyle="percent"
          percentInput="rate"
          maximumFractionDigits={0}
          tone={
            kpis.cashConversion === null
              ? 'default'
              : kpis.cashConversion >= 0.8
                ? 'success'
                : kpis.cashConversion >= 0.5
                  ? 'warning'
                  : 'danger'
          }
          subtitle="Operating cash flow / EBITDA"
          hint="How much of the period's EBITDA turned into actual cash."
        />
      </div>

      {/* ---- Visualisations ---------------------------------------------- */}
      <div className="mb-6">
        <WaterfallChart
          title="Cash Waterfall"
          hint="From opening to closing cash, bridged by the three activities."
          steps={statement.waterfall}
        />
      </div>

      <div className="mb-6 grid grid-cols-1 gap-4 lg:grid-cols-2">
        <TrendChart
          title="Monthly Cash Evolution"
          hint="Closing cash balance at each month end, and the movement that produced it."
          labels={statement.cashTrend.map((point) => point.label)}
          series={[
            {
              name: 'Closing cash',
              color: 'var(--primary)',
              values: statement.cashTrend.map((point) => point.endingCash),
              fill: true,
            },
            {
              name: 'Net change',
              color: 'var(--secondary)',
              values: statement.cashTrend.map((point) => point.netChange),
            },
          ]}
        />
        <CompositionDonut
          title="Cash Source Breakdown"
          hint="Every line that brought cash in over the period, largest first."
          slices={statement.sources}
          totalLabel="Total inflows"
          emptyMessage="No cash inflows in this period."
        />
      </div>

      <div className="mb-8">
        <TrendChart
          title="Operating vs Investing Trend"
          hint="Monthly operating and investing cash flow — a healthy business funds investment out of operations."
          labels={statement.activityTrend.map((point) => point.label)}
          series={[
            {
              name: 'Operating',
              color: 'var(--recovery-success)',
              values: statement.activityTrend.map((point) => point.operating),
              fill: true,
            },
            {
              name: 'Investing',
              color: 'var(--recovery-orange)',
              values: statement.activityTrend.map((point) => point.investing),
            },
          ]}
        />
      </div>

      {/* ---- Detail table ------------------------------------------------- */}
      <div className="mb-4">
        <PageTitle
          className="mb-4"
          hint="Full cash flow statement by activity and line — one column per month, plus the period total."
        >
          Cash Flow Statement
        </PageTitle>
      </div>

      <div className="overflow-x-auto rounded-lg border border-[var(--border)]">
        <table className="min-w-full border-collapse text-sm">
          <thead>
            <tr>
              <th className="sticky left-0 z-10 border-b border-[var(--border)] bg-[var(--secondary)] px-3 py-2 text-left text-xs font-semibold uppercase tracking-wide text-white">
                Line
              </th>
              {periods.map((period) => (
                <th
                  key={period.id}
                  className="border-b border-l border-[var(--border)] bg-[var(--secondary)] px-3 py-2 text-right text-xs font-semibold uppercase tracking-wide text-white whitespace-nowrap"
                >
                  {period.label}
                </th>
              ))}
              <th className="border-b border-l border-[var(--border)] bg-[var(--secondary)] px-3 py-2 text-right text-xs font-semibold uppercase tracking-wide text-white whitespace-nowrap">
                Total
              </th>
            </tr>
          </thead>
          <tbody>
            <AnchorRow
              label="Opening cash"
              periodIds={periods.map((p) => p.id)}
              amounts={Object.fromEntries(
                statement.cashTrend.map((point) => [point.period, point.openingCash]),
              )}
              total={kpis.openingCash}
            />
            {statement.activities.map((activity) => (
              <ActivityRows
                key={activity.id}
                activity={activity}
                periodIds={periods.map((p) => p.id)}
              />
            ))}
            <AnchorRow
              label="Net change in cash"
              periodIds={periods.map((p) => p.id)}
              amounts={Object.fromEntries(
                statement.cashTrend.map((point) => [point.period, point.netChange]),
              )}
              total={kpis.netChange}
            />
            <AnchorRow
              label="Closing cash"
              periodIds={periods.map((p) => p.id)}
              amounts={Object.fromEntries(
                statement.cashTrend.map((point) => [point.period, point.endingCash]),
              )}
              total={kpis.endingCash}
            />
          </tbody>
        </table>
      </div>
    </div>
  );
}

/** Opening / net change / closing — cash balances framing the activities. */
function AnchorRow({
  label,
  periodIds,
  amounts,
  total,
}: {
  label: string;
  periodIds: string[];
  amounts: Record<string, number>;
  total: number;
}) {
  return (
    <tr className="border-b border-t border-[var(--border)] bg-[color-mix(in_srgb,var(--secondary)_10%,var(--surface))]">
      <td className="sticky left-0 z-10 bg-[color-mix(in_srgb,var(--secondary)_10%,var(--surface))] px-3 py-2 text-xs font-semibold uppercase tracking-wide">
        {label}
      </td>
      {periodIds.map((periodId) => {
        const value = amounts[periodId] ?? 0;
        return (
          <td
            key={`${label}-${periodId}`}
            className={`border-l border-[var(--border)] px-3 py-2 text-right font-semibold whitespace-nowrap ${amountClassName(value)}`}
          >
            {formatAmount(value)}
          </td>
        );
      })}
      <td
        className={`border-l border-[var(--border)] px-3 py-2 text-right font-semibold whitespace-nowrap ${amountClassName(total)}`}
      >
        {formatAmount(total)}
      </td>
    </tr>
  );
}

function ActivityRows({
  activity,
  periodIds,
}: {
  activity: CfActivityRow;
  periodIds: string[];
}) {
  return (
    <Fragment>
      <tr className="border-b border-t border-[var(--border)] bg-[color-mix(in_srgb,var(--secondary)_6%,var(--surface))]">
        <td className="sticky left-0 z-10 bg-[color-mix(in_srgb,var(--secondary)_6%,var(--surface))] px-3 py-2 text-xs font-semibold uppercase tracking-wide">
          {activity.label}
        </td>
        {periodIds.map((periodId) => (
          <td
            key={`${activity.id}-head-${periodId}`}
            className="border-l border-[var(--border)] px-3 py-2"
          />
        ))}
        <td className="border-l border-[var(--border)] px-3 py-2" />
      </tr>

      {activity.categories.map((category) => (
        <tr key={category.key} className="border-b border-[var(--border)]">
          <td className="sticky left-0 z-10 bg-[var(--surface)] px-3 py-1 pl-8 text-sm text-[var(--text-muted)]">
            {category.label}
          </td>
          {periodIds.map((periodId) => {
            const value = category.amounts[periodId] ?? 0;
            return (
              <td
                key={`${category.key}-${periodId}`}
                className={`border-l border-[var(--border)] px-3 py-1 text-right whitespace-nowrap ${amountClassName(value)}`}
              >
                {formatAmount(value)}
              </td>
            );
          })}
          <td
            className={`border-l border-[var(--border)] px-3 py-1 text-right whitespace-nowrap ${amountClassName(category.total)}`}
          >
            {formatAmount(category.total)}
          </td>
        </tr>
      ))}

      <tr className="border-b border-[var(--border)]">
        <td className="sticky left-0 z-10 bg-[var(--surface)] px-3 py-1.5 pl-6 text-sm font-medium">
          Net cash from {activity.label.toLowerCase()}
        </td>
        {periodIds.map((periodId) => {
          const value = activity.amounts[periodId] ?? 0;
          return (
            <td
              key={`${activity.id}-total-${periodId}`}
              className={`border-l border-[var(--border)] px-3 py-1.5 text-right font-medium whitespace-nowrap ${amountClassName(value)}`}
            >
              {formatAmount(value)}
            </td>
          );
        })}
        <td
          className={`border-l border-[var(--border)] px-3 py-1.5 text-right font-medium whitespace-nowrap ${amountClassName(activity.total)}`}
        >
          {formatAmount(activity.total)}
        </td>
      </tr>
    </Fragment>
  );
}
