config:
    storage_name: abi
    workspace_id: "0c418524-fde3-4818-a961-931bde03df53"
    
schedulers:
  - name: onboarding
    abi_version: latest
    runs-on: self-hosted
    enabled: true
    cron: '0 * * * *'
    steps:
      - type: notebook
        name: sendgrid_update
        enabled: true
        entrypoint: models/scripts/operations-engine/Onboarding_Add_Users_to_SendGrid.ipynb
      - type: notebook
        name: hubspot_update
        enabled: true
        entrypoint: models/scripts/operations-engine/Naas_Users_Workflow_Onboarding.ipynb
  - name: connect
    abi_version: latest
    runs-on: self-hosted
    enabled: true
    cron: '0 12,17 * * 1-5'
    steps:
      - type: notebook
        name: linkedin_connect
        enabled: true
        entrypoint: models/scripts/operations-engine/Onboarding_Send_Invitation_LinkedIn.ipynb
  - name: opendata-aimodels_news
    abi_version: latest
    runs-on: self-hosted
    enabled: true
    cron: '0 12 * * *'
    steps:
      - type: notebook
        name: usage
        enabled: true
        entrypoint: models/scripts/opendata-engine/NewsAPI_Follow_AImodels_News.ipynb