name: /Users/maximejublou/dev/naas/abi/.abi-conda
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=2.4.1
  - backcall=0.2.0
  - bzip2=1.0.8
  - ca-certificates=2024.6.2
  - comm=0.2.2
  - debugpy=1.8.2
  - decorator=5.1.1
  - executing=2.0.1
  - importlib-metadata=8.0.0
  - importlib_metadata=8.0.0
  - ipykernel=6.29.4
  - ipython=8.18.1
  - jedi=0.19.1
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libcxx=17.0.6
  - libedit=3.1.20191231
  - libffi=3.4.2
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.3.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.47
  - prompt_toolkit=3.0.47
  - psutil=6.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.18.0
  - python=3.9.19
  - python_abi=3.9
  - pyzmq=26.0.3
  - readline=8.2
  - setuptools=70.1.1
  - six=1.16.0
  - tk=8.6.13
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2024a
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.2.6
  - zeromq=4.3.5
  - zipp=3.19.2
  - pip:
    - aiohttp==3.9.5
    - aiosignal==1.3.1
    - annotated-types==0.7.0
    - ansicolors==1.1.8
    - anyio==4.4.0
    - async-timeout==4.0.3
    - attrs==23.2.0
    - beautifulsoup4==4.12.3
    - boto3==1.34.128
    - botocore==1.34.136
    - cachetools==5.3.3
    - certifi==2024.6.2
    - charset-normalizer==3.3.2
    - click==8.1.7
    - colorama==0.4.6
    - dataclasses-json==0.6.7
    - distro==1.9.0
    - entrypoints==0.4
    - exceptiongroup==1.2.1
    - fastjsonschema==2.20.0
    - frozenlist==1.4.1
    - google==3.0.0
    - greenlet==3.0.3
    - grpcio==1.64.1
    - h11==0.14.0
    - httpcore==1.0.5
    - httpx==0.27.0
    - idna==3.7
    - jinja2==3.1.4
    - jmespath==1.0.1
    - jsonpatch==1.33
    - jsonpickle==3.2.2
    - jsonpointer==3.0.0
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - langchain==0.1.17
    - langchain-community==0.0.38
    - langchain-core==0.1.52
    - langchain-openai==0.1.6
    - langchain-text-splitters==0.0.2
    - langsmith==0.1.82
    - lxml==5.2.2
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - marshmallow==3.21.3
    - mdurl==0.1.2
    - mprop==0.16.0
    - multidict==6.0.5
    - mypy-extensions==1.0.0
    - mypy-protobuf==3.6.0
    - naas-data-product==0.1.9
    - naas-drivers[emailbuilder]==0.121.10
    - naas-models==1.11.6
    - naas-python==1.4.2
    - nbclient==0.10.0
    - nbformat==5.10.4
    - neo4j==5.18.0
    - networkx==3.2.1
    - numpy==1.19.5
    - openai==1.26.0
    - orjson==3.10.5
    - packaging==23.2
    - pandas==1.2.4
    - pandas-datareader==0.9.0
    - papermill==2.6.0
    - protobuf==5.27.2
    - protobuf-to-pydantic==0.2.6.2
    - pycountry==23.12.11
    - pydantic==2.7.4
    - pydantic-core==2.18.4
    - pydash==7.0.7
    - python-dateutil==2.9.0.post0
    - pytz==2024.1
    - pyvis==0.2.1
    - pyyaml==6.0.1
    - referencing==0.35.1
    - regex==2024.5.15
    - requests==2.32.3
    - rich==13.7.1
    - rpds-py==0.19.0
    - s3transfer==0.10.2
    - shellingham==1.5.4
    - sniffio==1.3.1
    - soupsieve==2.5
    - sqlalchemy==2.0.31
    - stack-data==0.6.3
    - tenacity==8.4.2
    - tiktoken==0.7.0
    - tqdm==4.66.4
    - typer==0.9.4
    - types-protobuf==5.27.0.20240626
    - typing-inspect==0.9.0
    - unidecode==1.3.7
    - urllib3==1.26.19
    - yarl==1.9.4

