entities:
  - ENTITY: 'Firstname Lastname'
    LINKEDIN_URL: 'https://www.linkedin.com/in/xxxx'
    LINKEDIN_LI_AT: 'NA'
    LINKEDIN_JSESSIONID: 'NA'
    EMAILS: ''
    WORKSPACE_IDS: ''
    PROMPT_SALES_MESSAGINGS: "Create 3 messaging options to engage conversation with a person on LinkedIn, be brief, concise, casual but professional. Do not speak as the author of the post but as a member of his sales team. Don't be salesy, try to build meaningful relationship based on the person interests."
    ICP_PEOPLE_SENIORITY: 'Professional/Staff, Senior Professional/Staff, Lead/Supervisor, Manager, Senior Manager, Executive, Top Executive'
    ICP_ORG_STAFF_RANGE_NAME: 'Solopreneur (0-1), Micro Team (2-10), Small Company (11-50), Medium Company (51-200), Large Company (201-500), Enterprise Level (501-1000), Major Corporation(1001-5000) , Global Corporation (5001-10000), Mega Corporation (10001>)'
    ICP_PEOPLE_DEPARTMENT: 'NA'
    ICP_ORG_NAME: 'NA'
    ICP_ORG_INDUSTRY: 'NA'
    ICP_ORG_COUNTRY: 'NA'
