config:
    storage_name: abi
    workspace_id: false
    
schedulers:
  - name: main
    enabled: true
    cron: '*/5 * * * *'
    steps:
      - type: notebook
        name: Run pipeline
        enabled: true
        entrypoint: tests/ci.ipynb
        environment_variables:
          CUSTOM_ENV_VAR: Hello World!
        inputs:
          notifications: false
          steps: ["opendata", "content", "growth", "sales", "ops", "finance"]
          message: "Hello scheduler!"
      - type: notebook
        name: Run Second step
        enabled: true
        entrypoint: tests/ci.ipynb
        inputs:
          notifications: false
          steps: ["opendata", "content", "growth", "sales", "ops", "finance"]
          message: "Hello scheduler!"