# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: naas_abi_proto/secret/v1/secret.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'naas_abi_proto/secret/v1/secret.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from naas_abi_proto.common.v1 import common_pb2 as naas__abi__proto_dot_common_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%naas_abi_proto/secret/v1/secret.proto\x12\rabi.secret.v1\x1a%naas_abi_proto/common/v1/common.proto\"F\n\nGetRequest\x12+\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x1a.abi.common.v1.CallContext\x12\x0b\n\x03key\x18\x02 \x01(\t\")\n\tGetResult\x12\x12\n\x05value\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_value\"m\n\x0bGetResponse\x12)\n\x05\x66ound\x18\x01 \x01(\x0b\x32\x18.abi.secret.v1.GetResultH\x00\x12)\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x18.abi.common.v1.CallErrorH\x00\x42\x08\n\x06result\"U\n\nSetRequest\x12+\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x1a.abi.common.v1.CallContext\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"E\n\x0bSetResponse\x12,\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x18.abi.common.v1.CallErrorH\x00\x88\x01\x01\x42\x08\n\x06_error\"I\n\rRemoveRequest\x12+\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x1a.abi.common.v1.CallContext\x12\x0b\n\x03key\x18\x02 \x01(\t\"H\n\x0eRemoveResponse\x12,\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x18.abi.common.v1.CallErrorH\x00\x88\x01\x01\x42\x08\n\x06_error\":\n\x0bListRequest\x12+\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x1a.abi.common.v1.CallContext\"8\n\x0bSecretEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x12\n\x05value\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_value\"9\n\nListResult\x12+\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1a.abi.secret.v1.SecretEntry\"o\n\x0cListResponse\x12*\n\x05\x66ound\x18\x01 \x01(\x0b\x32\x19.abi.secret.v1.ListResultH\x00\x12)\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x18.abi.common.v1.CallErrorH\x00\x42\x08\n\x06resultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'naas_abi_proto.secret.v1.secret_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETREQUEST']._serialized_start=95
  _globals['_GETREQUEST']._serialized_end=165
  _globals['_GETRESULT']._serialized_start=167
  _globals['_GETRESULT']._serialized_end=208
  _globals['_GETRESPONSE']._serialized_start=210
  _globals['_GETRESPONSE']._serialized_end=319
  _globals['_SETREQUEST']._serialized_start=321
  _globals['_SETREQUEST']._serialized_end=406
  _globals['_SETRESPONSE']._serialized_start=408
  _globals['_SETRESPONSE']._serialized_end=477
  _globals['_REMOVEREQUEST']._serialized_start=479
  _globals['_REMOVEREQUEST']._serialized_end=552
  _globals['_REMOVERESPONSE']._serialized_start=554
  _globals['_REMOVERESPONSE']._serialized_end=626
  _globals['_LISTREQUEST']._serialized_start=628
  _globals['_LISTREQUEST']._serialized_end=686
  _globals['_SECRETENTRY']._serialized_start=688
  _globals['_SECRETENTRY']._serialized_end=744
  _globals['_LISTRESULT']._serialized_start=746
  _globals['_LISTRESULT']._serialized_end=803
  _globals['_LISTRESPONSE']._serialized_start=805
  _globals['_LISTRESPONSE']._serialized_end=916
# @@protoc_insertion_point(module_scope)
