# Generated by tools/generate_services.py; do not edit.
from __future__ import annotations

from naas_abi_sdk.services._codec import ServiceProxy
from naas_abi_sdk.services.models import ActivityEvent, ActivityLogQuery


class ActivityLogService(ServiceProxy):
    domain = "activity_log"

    async def record(self, event: ActivityEvent) -> None:
        return await self._request("record", event=event)

    async def query(
        self, actor_id: str, query: ActivityLogQuery | None = None
    ) -> list[ActivityEvent]:
        return await self._request("query", actor_id=actor_id, query=query)

    async def list_actors(self) -> list[str]:
        return await self._request(
            "list_actors",
        )

    async def shutdown(self) -> None:
        return await self._request(
            "shutdown",
        )
