# Generated by tools/generate_services.py; do not edit.
from __future__ import annotations

from naas_abi_sdk.services._codec import ServiceProxy
from naas_abi_sdk.services.models import (
    WorkspaceAccess,
    WorkspaceStatus,
    WorkspaceTemplate,
)


class CodingEnvironmentService(ServiceProxy):
    domain = "coding_environment"

    async def ensure_user(self, *, external_id: str, email: str, username: str) -> str:
        return await self._request(
            "ensure_user", external_id=external_id, email=email, username=username
        )

    async def list_templates(self) -> list[WorkspaceTemplate]:
        return await self._request(
            "list_templates",
        )

    async def provision(
        self,
        *,
        user_id: str,
        template_id: str,
        name: str,
        params: dict[str, str] | None = None,
    ) -> WorkspaceStatus:
        return await self._request(
            "provision",
            user_id=user_id,
            template_id=template_id,
            name=name,
            params=params,
        )

    async def start(
        self, *, workspace_id: str, params: dict[str, str] | None = None
    ) -> WorkspaceStatus:
        return await self._request("start", workspace_id=workspace_id, params=params)

    async def stop(self, *, workspace_id: str) -> WorkspaceStatus:
        return await self._request("stop", workspace_id=workspace_id)

    async def delete(self, *, workspace_id: str) -> None:
        return await self._request("delete", workspace_id=workspace_id)

    async def list_environments(self, *, user_id: str) -> list[WorkspaceStatus]:
        return await self._request("list_environments", user_id=user_id)

    async def get_status(self, *, workspace_id: str) -> WorkspaceStatus:
        return await self._request("get_status", workspace_id=workspace_id)

    async def get_logs(self, *, workspace_id: str) -> list[str]:
        return await self._request("get_logs", workspace_id=workspace_id)

    async def get_access(
        self, *, workspace_id: str, user_id: str, app_slug: str
    ) -> WorkspaceAccess:
        return await self._request(
            "get_access", workspace_id=workspace_id, user_id=user_id, app_slug=app_slug
        )
