# Generated by tools/generate_services.py; do not edit.
from __future__ import annotations

from naas_abi_sdk.services._codec import ServiceProxy
from naas_abi_sdk.services.models import EmailAttachment


class EmailService(ServiceProxy):
    domain = "email"

    async def send(
        self,
        *,
        to_email: str | None = None,
        subject: str,
        text_body: str,
        html_body: str | None = None,
        from_email: str,
        from_name: str | None = None,
        reply_to: str | None = None,
        attachments: list[EmailAttachment] | None = None,
        to_emails: list[str] | str | None = None,
        cc_emails: list[str] | str | None = None,
    ) -> None:
        return await self._request(
            "send",
            to_email=to_email,
            subject=subject,
            text_body=text_body,
            html_body=html_body,
            from_email=from_email,
            from_name=from_name,
            reply_to=reply_to,
            attachments=attachments,
            to_emails=to_emails,
            cc_emails=cc_emails,
        )
