# Generated by tools/generate_services.py; do not edit.
from __future__ import annotations

from naas_abi_sdk.services._codec import ServiceProxy
from naas_abi_sdk.services.models import (
    Branch,
    Check,
    Comment,
    Commit,
    ContentEntry,
    Diff,
    FileContent,
    FileWrite,
    MergeResult,
    Proposal,
    Repo,
    Review,
    WorkflowRun,
)


class SourceControlService(ServiceProxy):
    domain = "source_control"

    async def ensure_user(self, *, external_id: str, email: str, username: str) -> str:
        return await self._request(
            "ensure_user", external_id=external_id, email=email, username=username
        )

    async def ensure_repo(
        self, *, owner: str, name: str, private: bool = True, auto_init: bool = True
    ) -> Repo:
        return await self._request(
            "ensure_repo", owner=owner, name=name, private=private, auto_init=auto_init
        )

    async def list_repos(self) -> list[Repo]:
        return await self._request(
            "list_repos",
        )

    async def add_collaborator(
        self, *, repo_id: str, username: str, permission: str = "write"
    ) -> None:
        return await self._request(
            "add_collaborator",
            repo_id=repo_id,
            username=username,
            permission=permission,
        )

    async def list_contents(
        self, *, repo_id: str, path: str = "", ref: str | None = None
    ) -> list[ContentEntry]:
        return await self._request("list_contents", repo_id=repo_id, path=path, ref=ref)

    async def get_file(
        self, *, repo_id: str, path: str, ref: str | None = None
    ) -> FileContent:
        return await self._request("get_file", repo_id=repo_id, path=path, ref=ref)

    async def upsert_file(
        self,
        *,
        repo_id: str,
        path: str,
        content: str | bytes,
        message: str,
        branch: str,
        author_name: str | None = None,
        author_email: str | None = None,
    ) -> Commit:
        return await self._request(
            "upsert_file",
            repo_id=repo_id,
            path=path,
            content=content,
            message=message,
            branch=branch,
            author_name=author_name,
            author_email=author_email,
        )

    async def upsert_files(
        self,
        *,
        repo_id: str,
        files: list[FileWrite],
        message: str,
        branch: str,
        author_name: str | None = None,
        author_email: str | None = None,
    ) -> Commit:
        return await self._request(
            "upsert_files",
            repo_id=repo_id,
            files=files,
            message=message,
            branch=branch,
            author_name=author_name,
            author_email=author_email,
        )

    async def list_commits(
        self, *, repo_id: str, ref: str | None = None, limit: int = 20
    ) -> list[Commit]:
        return await self._request(
            "list_commits", repo_id=repo_id, ref=ref, limit=limit
        )

    async def list_branches(self, *, repo_id: str) -> list[Branch]:
        return await self._request("list_branches", repo_id=repo_id)

    async def create_branch(self, *, repo_id: str, name: str, from_ref: str) -> Branch:
        return await self._request(
            "create_branch", repo_id=repo_id, name=name, from_ref=from_ref
        )

    async def delete_branch(self, *, repo_id: str, name: str) -> None:
        return await self._request("delete_branch", repo_id=repo_id, name=name)

    async def get_diff(self, *, repo_id: str, base: str, head: str) -> Diff:
        return await self._request("get_diff", repo_id=repo_id, base=base, head=head)

    async def create_proposal(
        self,
        *,
        repo_id: str,
        title: str,
        body: str,
        source_branch: str,
        target_branch: str,
        reviewers: list[str] | None = None,
    ) -> Proposal:
        return await self._request(
            "create_proposal",
            repo_id=repo_id,
            title=title,
            body=body,
            source_branch=source_branch,
            target_branch=target_branch,
            reviewers=reviewers,
        )

    async def list_proposals(
        self, *, repo_id: str, state: str = "open"
    ) -> list[Proposal]:
        return await self._request("list_proposals", repo_id=repo_id, state=state)

    async def get_proposal(self, *, repo_id: str, number: int) -> Proposal:
        return await self._request("get_proposal", repo_id=repo_id, number=number)

    async def get_proposal_diff(self, *, repo_id: str, number: int) -> Diff:
        return await self._request("get_proposal_diff", repo_id=repo_id, number=number)

    async def list_proposal_commits(self, *, repo_id: str, number: int) -> list[Commit]:
        return await self._request(
            "list_proposal_commits", repo_id=repo_id, number=number
        )

    async def list_comments(self, *, repo_id: str, number: int) -> list[Comment]:
        return await self._request("list_comments", repo_id=repo_id, number=number)

    async def list_reviews(self, *, repo_id: str, number: int) -> list[Review]:
        return await self._request("list_reviews", repo_id=repo_id, number=number)

    async def list_workflow_runs(
        self, *, repo_id: str, limit: int = 20
    ) -> list[WorkflowRun]:
        return await self._request("list_workflow_runs", repo_id=repo_id, limit=limit)

    async def add_comment(
        self,
        *,
        repo_id: str,
        number: int,
        body: str,
        path: str | None = None,
        line: int | None = None,
    ) -> Comment:
        return await self._request(
            "add_comment",
            repo_id=repo_id,
            number=number,
            body=body,
            path=path,
            line=line,
        )

    async def submit_review(
        self, *, repo_id: str, number: int, event: str, body: str = ""
    ) -> Review:
        return await self._request(
            "submit_review", repo_id=repo_id, number=number, event=event, body=body
        )

    async def list_checks(self, *, repo_id: str, number: int) -> list[Check]:
        return await self._request("list_checks", repo_id=repo_id, number=number)

    async def set_branch_protection(
        self,
        *,
        repo_id: str,
        branch: str,
        required_approvals: int,
        required_checks: list[str],
    ) -> None:
        return await self._request(
            "set_branch_protection",
            repo_id=repo_id,
            branch=branch,
            required_approvals=required_approvals,
            required_checks=required_checks,
        )

    async def merge(
        self, *, repo_id: str, number: int, method: str = "merge"
    ) -> MergeResult:
        return await self._request(
            "merge", repo_id=repo_id, number=number, method=method
        )

    async def mint_git_token(self, *, user_id: str) -> str:
        return await self._request("mint_git_token", user_id=user_id)
