# Generated by tools/generate_services.py; do not edit.
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any


@dataclass
class ObjectMetaData:
    file_path: str = ""
    file_name: str = ""
    file_size_bytes: int = 0
    created_time: datetime | None = None
    modified_time: datetime | None = None
    accessed_time: datetime | None = None
    permissions: str | None = None
    mime_type: str | None = None
    encoding: str | None = None


@dataclass
class ActivityEvent:
    actor_id: str = ""
    event_type: str = ""
    timestamp: datetime | None = field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    correlation_id: str | None = None
    attributes: dict[str, Any] | None = None


@dataclass
class ActivityLogQuery:
    event_type: str | None = None
    since: datetime | None = None
    until: datetime | None = None
    limit: int | None = None


@dataclass
class WorkspaceTemplate:
    id: str = ""
    name: str = ""
    active_version_id: str = ""


@dataclass
class WorkspaceStatus:
    id: str = ""
    name: str = ""
    phase: str = ""
    agent_ready: bool = False


@dataclass
class WorkspaceAccess:
    url: str = ""
    token: str | None = None
    expires_at: str | None = None


@dataclass
class Repo:
    id: str = ""
    name: str = ""
    owner: str = ""
    default_branch: str = ""
    clone_url: str = ""
    html_url: str = ""
    description: str = ""
    private: bool = False
    empty: bool = False
    updated_at: str | None = None


@dataclass
class ContentEntry:
    name: str = ""
    path: str = ""
    type: str = ""
    size: int = 0


@dataclass
class FileContent:
    path: str = ""
    name: str = ""
    size: int = 0
    text: str | None = None
    is_binary: bool = False
    data: bytes | None = None


@dataclass
class Commit:
    sha: str = ""
    message: str = ""
    author: str = ""
    date: str | None = None


@dataclass
class Branch:
    name: str = ""
    commit_sha: str = ""
    protected: bool = False


@dataclass
class DiffFile:
    path: str = ""
    status: str = ""
    additions: int = 0
    deletions: int = 0
    patch: str | None = None
    old_path: str | None = None


@dataclass
class Diff:
    files: list[DiffFile] = field(default_factory=list)


@dataclass
class Comment:
    id: str = ""
    path: str | None = None
    line: int | None = None
    body: str = ""
    author: str = ""
    created_at: str | None = None


@dataclass
class Review:
    id: str = ""
    state: str = ""
    body: str = ""
    author: str = ""
    submitted_at: str | None = None


@dataclass
class Check:
    name: str = ""
    status: str = ""
    conclusion: str | None = None


@dataclass
class Proposal:
    id: str = ""
    number: int = 0
    title: str = ""
    body: str = ""
    state: str = ""
    source_branch: str = ""
    target_branch: str = ""
    author: str = ""
    mergeable: bool = False
    approvals: int = 0
    html_url: str = ""


@dataclass
class WorkflowRun:
    id: int = 0
    name: str = ""
    workflow_id: str = ""
    display_title: str = ""
    run_number: int = 0
    event: str = ""
    status: str = ""
    head_branch: str = ""
    head_sha: str = ""
    url: str = ""
    created_at: str | None = None
    run_started_at: str | None = None
    updated_at: str | None = None


@dataclass
class MergeResult:
    merged: bool = False
    sha: str | None = None
    message: str | None = None


@dataclass
class ColumnSpec:
    name: str = ""
    type: str = "string"


@dataclass
class PartitionSpec:
    column: str = ""
    transform: str = "identity"


@dataclass
class DatasetSpec:
    name: str = ""
    namespace: str = "default"
    columns: list[ColumnSpec] = field(default_factory=list)
    partitions: list[PartitionSpec] = field(default_factory=list)
    primary_key: list[str] = field(default_factory=list)


@dataclass
class DatasetInfo:
    name: str = ""
    namespace: str = "default"
    columns: list[ColumnSpec] = field(default_factory=list)
    partitions: list[PartitionSpec] = field(default_factory=list)
    primary_key: list[str] = field(default_factory=list)
    snapshot_id: int = 0
    location: str = ""


@dataclass
class DatasetSnapshotInfo:
    snapshot_id: int = 0
    created_at: datetime | None = None


@dataclass
class QueryResult:
    columns: list[str] = field(default_factory=list)
    rows: list[dict[str, Any]] = field(default_factory=list)


@dataclass
class EmailAttachment:
    filename: str = ""
    content: bytes = b""
    mime_type: str = ""
    content_id: str | None = None
    is_inline: bool = False


@dataclass
class VectorDocument:
    id: str = ""
    vector: list[float] | None = None
    metadata: dict[str, Any] | None = None
    payload: dict[str, Any] | None = None


@dataclass
class SearchResult:
    id: str = ""
    score: float = 0.0
    vector: list[float] | None = None
    metadata: dict[str, Any] | None = None
    payload: dict[str, Any] | None = None


@dataclass
class StoredEvent:
    id: str = ""
    event_type: str = ""
    seq: int = 0
    timestamp: str = ""
    payload: bytes = b""


@dataclass
class FileWrite:
    path: str
    content: str | bytes


@dataclass
class FieldSpec:
    name: str
    type: str
    indexed: bool = False
    unique: bool = False


@dataclass
class CollectionSpec:
    name: str
    fields: tuple[FieldSpec, ...] = ()
    unique_together: tuple[tuple[str, ...], ...] = ()


@dataclass
class Document:
    id: str
    data: dict[str, Any]
    created_at: datetime
    updated_at: datetime
    version: int


@dataclass
class Page:
    items: list[Document]
    cursor: str | None


DTO_TYPES = {
    "abi.object_storage.v1.ObjectMetaData": ObjectMetaData,
    "abi.activity_log.v1.ActivityEvent": ActivityEvent,
    "abi.activity_log.v1.ActivityLogQueryFilter": ActivityLogQuery,
    "abi.coding_environment.v1.WorkspaceTemplate": WorkspaceTemplate,
    "abi.coding_environment.v1.WorkspaceStatus": WorkspaceStatus,
    "abi.coding_environment.v1.WorkspaceAccess": WorkspaceAccess,
    "abi.source_control.v1.Repo": Repo,
    "abi.source_control.v1.ContentEntry": ContentEntry,
    "abi.source_control.v1.FileContent": FileContent,
    "abi.source_control.v1.Commit": Commit,
    "abi.source_control.v1.Branch": Branch,
    "abi.source_control.v1.DiffFile": DiffFile,
    "abi.source_control.v1.Diff": Diff,
    "abi.source_control.v1.Comment": Comment,
    "abi.source_control.v1.Review": Review,
    "abi.source_control.v1.Check": Check,
    "abi.source_control.v1.Proposal": Proposal,
    "abi.source_control.v1.WorkflowRun": WorkflowRun,
    "abi.source_control.v1.MergeResult": MergeResult,
    "abi.dataset.v1.ColumnSpec": ColumnSpec,
    "abi.dataset.v1.PartitionSpec": PartitionSpec,
    "abi.dataset.v1.DatasetSpec": DatasetSpec,
    "abi.dataset.v1.DatasetInfo": DatasetInfo,
    "abi.dataset.v1.DatasetSnapshotInfo": DatasetSnapshotInfo,
    "abi.dataset.v1.QueryResult": QueryResult,
    "abi.email.v1.EmailAttachment": EmailAttachment,
    "abi.vector_store.v1.VectorDocument": VectorDocument,
    "abi.vector_store.v1.SearchResult": SearchResult,
    "abi.event.v1.StoredEvent": StoredEvent,
}
