#!/usr/bin/env python3
"""Generate Periodic Table element fragments and the Nexus modules ontology.

Canonical catalog document (owl:Ontology, under ontologies/modules/):
    naas_abi/ontologies/modules/PeriodicTableOntology.ttl

Authoring inputs (not listed by Nexus list_ontology_files):
    schema.ttl       section classes + properties
    elements/*.ttl   one fragment per element

Run from the ABI repo root:
    uv run python libs/naas-abi/naas_abi/ontologies/periodic_table/generate_elements.py
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

ELEMENTS_DIR = Path(__file__).parent / "elements"
SCHEMA_PATH = Path(__file__).parent / "schema.ttl"
MODULES_ONTOLOGY_PATH = Path(__file__).parent.parent / "modules" / "PeriodicTableOntology.ttl"

PREFIXES = """\
@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix owl:  <http://www.w3.org/2002/07/owl#> .
@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix dc:   <http://purl.org/dc/terms/> .
@prefix dc11: <http://purl.org/dc/elements/1.1/> .
@prefix bfo:  <http://purl.obolibrary.org/obo/> .
@prefix cco:  <https://www.commoncoreontologies.org/> .
@prefix abi:  <http://ontology.naas.ai/abi/> .
@prefix zen:  <http://ontology.naas.ai/zen/> .
@prefix pts:  <http://ontology.naas.ai/zen/pts/> .

"""

ONTOLOGY_HEADER = """\
# Canonical Periodic Table ontology for Nexus (ontologies/modules/).
# Generated by generate_elements.py from schema.ttl + elements/*.ttl.
# Import chain: BFO core -> BFO 7 Buckets -> ABI Ontology -> Periodic Table

abi:PeriodicTableOntology a owl:Ontology ;
    dc:title "Periodic Table of Software Ontology"@en ;
    rdfs:label "Periodic Table of Software"@en ;
    dc:description "The essential elements for building any SaaS product or system, grounded in BFO 7 Buckets via ABI Ontology."@en ;
    dc:date "2026-08-18"^^xsd:date ;
    dc:license <https://creativecommons.org/licenses/by/4.0/> ;
    dc11:contributor "Jeremy Ravenel" ;
    rdfs:comment "Canonical modules ontology for ABI. Element authoring fragments live under ontologies/periodic_table/elements/; schema fragment under ontologies/periodic_table/schema.ttl."@en ;
    abi:pythonPackage "naas_abi" ;
    abi:ontologyResource "ontologies/modules/PeriodicTableOntology.ttl" ;
    abi:parentOntology abi:Ontology ;
    abi:importChain "BFO -> BFO7Buckets -> ABI -> Periodic Table"@en .

"""


@dataclass(frozen=True)
class Element:
    number: int
    local_name: str
    label: str
    section: str
    section_class: str
    bfo_bucket: str
    definition: str
    cco_equiv: str | None = None
    abi_equiv: str | None = None
    alt_label: str | None = None


# BFO 7 Buckets: human-readable ABI classes inherit BFO codes via owl:equivalentClass
BFO7_BUCKETS: dict[str, dict[str, str]] = {
    "material_entity": {
        "abi": "abi:MaterialEntity",
        "bfo": "bfo:BFO_0000040",
        "label": "Material entity (WHO)",
    },
    "process": {
        "abi": "abi:Process",
        "bfo": "bfo:BFO_0000015",
        "label": "Process (HOW)",
    },
    "site": {
        "abi": "abi:Site",
        "bfo": "bfo:BFO_0000029",
        "label": "Site (WHERE)",
    },
    "information_content_entity": {
        "abi": "abi:GenericallyDependentContinuant",
        "bfo": "bfo:BFO_0000031",
        "label": "Information content entity (WHAT)",
    },
    "quality": {
        "abi": "abi:Quality",
        "bfo": "bfo:BFO_0000019",
        "label": "Quality (WHICH)",
    },
    "realizable": {
        "abi": "abi:Role",
        "bfo": "bfo:BFO_0000023",
        "label": "Realizable (WHY)",
    },
    "temporal_region": {
        "abi": "abi:TemporalRegion",
        "bfo": "bfo:BFO_0000008",
        "label": "Temporal region (WHEN)",
    },
}


# fmt: off
ELEMENTS: list[Element] = [
    # Objects (1-35)
    Element(1, "Company", "Company", "object", "pts:SoftwareObject", "information_content_entity", "A business organization record in a software system.", abi_equiv="abi:Organization", cco_equiv="cco:ont00001180"),
    Element(2, "Person", "Person", "object", "pts:SoftwareObject", "material_entity", "A human being represented as a first-class entity.", abi_equiv="abi:Person", cco_equiv="cco:ont00001262"),
    Element(3, "Contact", "Contact", "object", "pts:SoftwareObject", "information_content_entity", "A record describing how to reach a person or organization."),
    Element(4, "Lead", "Lead", "object", "pts:SoftwareObject", "information_content_entity", "A prospective customer record before qualification."),
    Element(5, "Deal", "Deal", "object", "pts:SoftwareObject", "information_content_entity", "A commercial opportunity record tracking revenue potential."),
    Element(6, "Account", "Account", "object", "pts:SoftwareObject", "information_content_entity", "A customer or partner organization record in a CRM."),
    Element(7, "User", "User", "object", "pts:SoftwareObject", "material_entity", "An authenticated actor who interacts with the system.", alt_label="System user"),
    Element(8, "Team", "Team", "object", "pts:SoftwareObject", "material_entity", "A group of agents collaborating within the system."),
    Element(9, "Role", "Role", "object", "pts:SoftwareObject", "realizable", "A socially or institutionally grounded capacity assigned to a bearer.", abi_equiv="abi:Role"),
    Element(10, "Opportunity", "Opportunity", "object", "pts:SoftwareObject", "information_content_entity", "A qualified sales opportunity record."),
    Element(11, "Product", "Product", "object", "pts:SoftwareObject", "information_content_entity", "An offering catalog record, tangible or intangible."),
    Element(12, "Service", "Service", "object", "pts:SoftwareObject", "information_content_entity", "A service offering record describing work performed for a customer."),
    Element(13, "Project", "Project", "object", "pts:SoftwareObject", "information_content_entity", "A container record for coordinated work with a defined scope."),
    Element(14, "Task", "Task", "object", "pts:SoftwareObject", "information_content_entity", "A unit of work assigned to an agent."),
    Element(15, "Subtask", "Subtask", "object", "pts:SoftwareObject", "information_content_entity", "A child task decomposed from a parent task."),
    Element(16, "Doc", "Doc", "object", "pts:SoftwareObject", "information_content_entity", "A document content artifact.", abi_equiv="abi:DocumentContentEntity"),
    Element(17, "File", "File", "object", "pts:SoftwareObject", "information_content_entity", "A stored binary or text file record."),
    Element(18, "Note", "Note", "object", "pts:SoftwareObject", "information_content_entity", "A short free-form annotation attached to another record."),
    Element(19, "Event", "Event", "object", "pts:SoftwareObject", "process", "A scheduled or logged occurrence; as an object it is the record of that occurrence."),
    Element(20, "Meeting", "Meeting", "object", "pts:SoftwareObject", "process", "A synchronous gathering; as an object it is the meeting record."),
    Element(21, "Invoice", "Invoice", "object", "pts:SoftwareObject", "information_content_entity", "A billing document requesting payment."),
    Element(22, "Payment", "Payment", "object", "pts:SoftwareObject", "process", "A transfer of funds; as an object it is the payment record."),
    Element(23, "Subscription", "Subscription", "object", "pts:SoftwareObject", "information_content_entity", "A recurring billing relationship record."),
    Element(24, "Plan", "Plan", "object", "pts:SoftwareObject", "information_content_entity", "A pricing or entitlement tier definition."),
    Element(25, "Price", "Price", "object", "pts:SoftwareObject", "quality", "A monetary amount associated with an offering."),
    Element(26, "Campaign", "Campaign", "object", "pts:SoftwareObject", "information_content_entity", "A coordinated marketing outreach record."),
    Element(27, "MessageRecord", "Message", "object", "pts:SoftwareObject", "information_content_entity", "A stored communication artifact.", alt_label="Message"),
    Element(28, "EmailRecord", "Email", "object", "pts:SoftwareObject", "information_content_entity", "An email message record.", alt_label="Email"),
    Element(29, "CallRecord", "Call", "object", "pts:SoftwareObject", "process", "A phone or video call; as an object it is the call log.", alt_label="Call"),
    Element(30, "Activity", "Activity", "object", "pts:SoftwareObject", "information_content_entity", "A logged interaction or touchpoint on a record."),
    Element(31, "Workflow", "Workflow", "object", "pts:SoftwareObject", "information_content_entity", "A specification of ordered steps and transitions."),
    Element(32, "Template", "Template", "object", "pts:SoftwareObject", "information_content_entity", "A reusable pattern for creating other records."),
    Element(33, "Tag", "Tag", "object", "pts:SoftwareObject", "information_content_entity", "A lightweight label applied to records for classification."),
    Element(34, "Location", "Location", "object", "pts:SoftwareObject", "site", "A geographic or logical place referenced by records."),
    Element(35, "Vendor", "Vendor", "object", "pts:SoftwareObject", "information_content_entity", "A supplier organization record."),
    # Properties (36-60)
    Element(36, "Status", "Status", "property", "pts:SoftwareProperty", "quality", "The current lifecycle state of a record."),
    Element(37, "Boolean", "Boolean", "property", "pts:SoftwareProperty", "quality", "A true/false attribute value."),
    Element(38, "Date", "Date", "property", "pts:SoftwareProperty", "temporal_region", "A calendar date attribute."),
    Element(39, "DateTime", "DateTime", "property", "pts:SoftwareProperty", "temporal_region", "A timestamp attribute with date and time."),
    Element(40, "Number", "Number", "property", "pts:SoftwareProperty", "quality", "A numeric attribute value."),
    Element(41, "Currency", "Currency", "property", "pts:SoftwareProperty", "quality", "A monetary amount with currency context."),
    Element(42, "Percent", "Percent", "property", "pts:SoftwareProperty", "quality", "A ratio expressed as a percentage."),
    Element(43, "Text", "Text", "property", "pts:SoftwareProperty", "quality", "A free-form string attribute."),
    Element(44, "URL", "URL", "property", "pts:SoftwareProperty", "quality", "A web address attribute."),
    Element(45, "EmailAddress", "Email", "property", "pts:SoftwareProperty", "quality", "An email address attribute on a record.", alt_label="Email"),
    Element(46, "Phone", "Phone", "property", "pts:SoftwareProperty", "quality", "A telephone number attribute."),
    Element(47, "Address", "Address", "property", "pts:SoftwareProperty", "quality", "A postal or physical address attribute."),
    Element(48, "JSON", "JSON", "property", "pts:SoftwareProperty", "information_content_entity", "A structured JSON payload attribute."),
    Element(49, "Enum", "Enum", "property", "pts:SoftwareProperty", "information_content_entity", "A closed set of allowed values."),
    Element(50, "ID", "ID", "property", "pts:SoftwareProperty", "quality", "A unique identifier attribute."),
    Element(51, "Owner", "Owner", "property", "pts:SoftwareProperty", "realizable", "The agent role responsible for a record."),
    Element(52, "CreatedAt", "Created At", "property", "pts:SoftwareProperty", "temporal_region", "When a record was first created."),
    Element(53, "UpdatedAt", "Updated At", "property", "pts:SoftwareProperty", "temporal_region", "When a record was last modified."),
    Element(54, "StartDate", "Start Date", "property", "pts:SoftwareProperty", "temporal_region", "When something begins."),
    Element(55, "DueDate", "Due Date", "property", "pts:SoftwareProperty", "temporal_region", "When something is due."),
    Element(56, "Priority", "Priority", "property", "pts:SoftwareProperty", "quality", "The relative urgency of a record."),
    Element(57, "Score", "Score", "property", "pts:SoftwareProperty", "quality", "A numeric ranking or rating."),
    Element(58, "Count", "Count", "property", "pts:SoftwareProperty", "quality", "A quantity aggregate attribute."),
    Element(59, "Duration", "Duration", "property", "pts:SoftwareProperty", "temporal_region", "An elapsed time span."),
    Element(60, "Time", "Time", "property", "pts:SoftwareProperty", "temporal_region", "A time-of-day or temporal coordinate."),
    # Actions (61-85)
    Element(61, "Creating", "Create", "action", "pts:SoftwareAction", "process", "Instantiating a new record or artifact.", alt_label="Create"),
    Element(62, "Updating", "Update", "action", "pts:SoftwareAction", "process", "Modifying an existing record.", alt_label="Update"),
    Element(63, "Assigning", "Assign", "action", "pts:SoftwareAction", "process", "Allocating ownership or responsibility.", alt_label="Assign"),
    Element(64, "Deleting", "Delete", "action", "pts:SoftwareAction", "process", "Removing a record from active use.", alt_label="Delete"),
    Element(65, "Viewing", "View", "action", "pts:SoftwareAction", "process", "Reading or displaying a record.", alt_label="View"),
    Element(66, "Searching", "Search", "action", "pts:SoftwareAction", "process", "Querying records by criteria.", alt_label="Search"),
    Element(67, "Filtering", "Filter", "action", "pts:SoftwareAction", "process", "Narrowing a result set by constraints.", alt_label="Filter"),
    Element(68, "Sorting", "Sort", "action", "pts:SoftwareAction", "process", "Ordering records by attribute values.", alt_label="Sort"),
    Element(69, "Grouping", "Group", "action", "pts:SoftwareAction", "process", "Clustering records by shared attributes.", alt_label="Group"),
    Element(70, "Importing", "Import", "action", "pts:SoftwareAction", "process", "Loading external data into the system.", alt_label="Import"),
    Element(71, "Exporting", "Export", "action", "pts:SoftwareAction", "process", "Extracting records to an external format.", alt_label="Export"),
    Element(72, "Duplicating", "Duplicate", "action", "pts:SoftwareAction", "process", "Creating a copy of an existing record.", alt_label="Duplicate"),
    Element(73, "Notifying", "Notify", "action", "pts:SoftwareAction", "process", "Sending an alert to an agent.", alt_label="Notify"),
    Element(74, "Reminding", "Remind", "action", "pts:SoftwareAction", "process", "Scheduling a future notification.", alt_label="Remind"),
    Element(75, "Messaging", "Message", "action", "pts:SoftwareAction", "process", "Sending a communication to another agent.", alt_label="Message"),
    Element(76, "Approving", "Approve", "action", "pts:SoftwareAction", "process", "Granting authorization for a state change.", alt_label="Approve"),
    Element(77, "Rejecting", "Reject", "action", "pts:SoftwareAction", "process", "Denying authorization for a state change.", alt_label="Reject"),
    Element(78, "Archiving", "Archive", "action", "pts:SoftwareAction", "process", "Moving a record to inactive storage.", alt_label="Archive"),
    Element(79, "Restoring", "Restore", "action", "pts:SoftwareAction", "process", "Returning an archived record to active use.", alt_label="Restore"),
    Element(80, "Escalating", "Escalate", "action", "pts:SoftwareAction", "process", "Raising priority or routing to a higher authority.", alt_label="Escalate"),
    Element(81, "Triggering", "Trigger", "action", "pts:SoftwareAction", "process", "Initiating an automated response to an event.", alt_label="Trigger"),
    Element(82, "Scheduling", "Schedule", "action", "pts:SoftwareAction", "process", "Planning a process to run at a future time.", alt_label="Schedule"),
    Element(83, "Running", "Run", "action", "pts:SoftwareAction", "process", "Executing a process or job.", alt_label="Run"),
    Element(84, "Stopping", "Stop", "action", "pts:SoftwareAction", "process", "Halting an in-progress process.", alt_label="Stop"),
    Element(85, "Canceling", "Cancel", "action", "pts:SoftwareAction", "process", "Aborting a planned or running process.", alt_label="Cancel"),
    # Interfaces (86-100)
    Element(86, "GridView", "Grid", "interface", "pts:SoftwareInterface", "information_content_entity", "A tabular layout of records in rows and columns.", alt_label="Grid"),
    Element(87, "ListView", "List", "interface", "pts:SoftwareInterface", "information_content_entity", "A vertical list of record summaries.", alt_label="List"),
    Element(88, "KanbanView", "Kanban", "interface", "pts:SoftwareInterface", "information_content_entity", "A board organized by status columns.", alt_label="Kanban"),
    Element(89, "CalendarView", "Calendar", "interface", "pts:SoftwareInterface", "information_content_entity", "A time-based layout of events.", alt_label="Calendar"),
    Element(90, "GalleryView", "Gallery", "interface", "pts:SoftwareInterface", "information_content_entity", "A visual card grid emphasizing media.", alt_label="Gallery"),
    Element(91, "MapView", "Map", "interface", "pts:SoftwareInterface", "information_content_entity", "A geospatial visualization surface.", alt_label="Map"),
    Element(92, "TimelineView", "Timeline", "interface", "pts:SoftwareInterface", "information_content_entity", "A chronological sequence visualization.", alt_label="Timeline"),
    Element(93, "TableView", "Table", "interface", "pts:SoftwareInterface", "information_content_entity", "A dense data table with sortable columns.", alt_label="Table"),
    Element(94, "BoardView", "Board", "interface", "pts:SoftwareInterface", "information_content_entity", "A freeform spatial arrangement of cards.", alt_label="Board"),
    Element(95, "ChartView", "Chart", "interface", "pts:SoftwareInterface", "information_content_entity", "A graphical representation of aggregated data.", alt_label="Chart"),
    Element(96, "DetailView", "Detail", "interface", "pts:SoftwareInterface", "information_content_entity", "A single-record deep-dive layout.", alt_label="Detail"),
    Element(97, "CardView", "Card", "interface", "pts:SoftwareInterface", "information_content_entity", "A compact summary tile for one record.", alt_label="Card"),
    Element(98, "FeedView", "Feed", "interface", "pts:SoftwareInterface", "information_content_entity", "A reverse-chronological stream of updates.", alt_label="Feed"),
    Element(99, "FormView", "Form", "interface", "pts:SoftwareInterface", "information_content_entity", "An input layout for creating or editing records.", alt_label="Form"),
    Element(100, "TreeView", "Tree", "interface", "pts:SoftwareInterface", "information_content_entity", "A hierarchical parent-child navigation layout.", alt_label="Tree"),
    # Intelligence (101-108)
    Element(101, "IntelligenceSearch", "Search", "intelligence", "pts:SoftwareIntelligence", "process", "AI-assisted retrieval over unstructured or semantic data.", alt_label="Search"),
    Element(102, "Summarizing", "Summarize", "intelligence", "pts:SoftwareIntelligence", "process", "Condensing content while preserving meaning.", alt_label="Summarize"),
    Element(103, "Extracting", "Extract", "intelligence", "pts:SoftwareIntelligence", "process", "Pulling structured facts from unstructured input.", alt_label="Extract"),
    Element(104, "Classifying", "Classify", "intelligence", "pts:SoftwareIntelligence", "process", "Assigning categories or types to input.", alt_label="Classify"),
    Element(105, "Generating", "Generate", "intelligence", "pts:SoftwareIntelligence", "process", "Creating new content from a prompt or context.", alt_label="Generate"),
    Element(106, "Prompting", "Prompt", "intelligence", "pts:SoftwareIntelligence", "information_content_entity", "An instruction artifact that guides model behavior.", alt_label="Prompt"),
    Element(107, "Recommending", "Recommend", "intelligence", "pts:SoftwareIntelligence", "process", "Suggesting actions or items based on context.", alt_label="Recommend"),
    Element(108, "Analyzing", "Analyze", "intelligence", "pts:SoftwareIntelligence", "process", "Deriving insights from data or text.", alt_label="Analyze"),
    # Rules (109-115)
    Element(109, "Permission", "Permission", "rule", "pts:SoftwareRule", "realizable", "An authorization role governing access to resources."),
    Element(110, "Policy", "Policy", "rule", "pts:SoftwareRule", "information_content_entity", "A written rule set governing system behavior."),
    Element(111, "RuleTrigger", "Trigger", "rule", "pts:SoftwareRule", "information_content_entity", "A condition specification that starts an automation.", alt_label="Trigger"),
    Element(112, "RuleSchedule", "Schedule", "rule", "pts:SoftwareRule", "information_content_entity", "A temporal specification for recurring automation.", alt_label="Schedule"),
    Element(113, "Condition", "Condition", "rule", "pts:SoftwareRule", "information_content_entity", "A logical predicate evaluated before an action."),
    Element(114, "RuleAction", "Action", "rule", "pts:SoftwareRule", "information_content_entity", "A specified effect executed when a rule fires.", alt_label="Action"),
    Element(115, "Audit", "Audit", "rule", "pts:SoftwareRule", "information_content_entity", "An immutable trail of who did what and when."),
    # Collaboration interfaces (116-119)
    Element(116, "DocInterface", "Doc", "interface", "pts:SoftwareInterface", "information_content_entity", "A linear rich-text authoring canvas.", abi_equiv="abi:DocumentContentEntity", alt_label="Doc interface"),
    Element(117, "SheetInterface", "Sheet", "interface", "pts:SoftwareInterface", "information_content_entity", "An interactive cell-grid editing surface.", abi_equiv="abi:Spreadsheet", alt_label="Sheet interface"),
    Element(118, "SlideInterface", "Slide", "interface", "pts:SoftwareInterface", "information_content_entity", "A deck-based presentation canvas.", alt_label="Slide interface"),
    Element(119, "Portal", "Site", "interface", "pts:SoftwareInterface", "information_content_entity", "A published web portal or site layout (not a BFO site).", alt_label="Site interface"),
]
# fmt: on


def render_element(el: Element) -> str:
    bucket = BFO7_BUCKETS[el.bfo_bucket]
    lines = [
        PREFIXES,
        f"# Periodic Table element {el.number:03d}: {el.label}\n",
        f"pts:{el.local_name} a owl:Class ;",
        f'    rdfs:label "{el.label}"@en ;',
        f"    rdfs:subClassOf {el.section_class} ;",
        f'    pts:elementNumber "{el.number}"^^xsd:integer ;',
        f'    pts:section "{el.section}" ;',
        f'    pts:bfoBucket "{el.bfo_bucket}" ;',
        f'    pts:bfoBucketLabel "{bucket["label"]}" ;',
        f"    zen:mapsToBFOBucket {bucket['abi']} ;",
        f"    zen:mapsToBFOCode {bucket['bfo']} ;",
        f'    skos:definition "{el.definition}"@en',
    ]
    if el.alt_label:
        lines[-1] += " ;"
        lines.append(f'    skos:altLabel "{el.alt_label}"@en')
    if el.abi_equiv:
        if not lines[-1].endswith(";"):
            lines[-1] += " ;"
        else:
            pass
        if lines[-1].endswith("@en"):
            lines[-1] = lines[-1].rstrip() + " ;"
        lines.append(f"    owl:equivalentClass {el.abi_equiv}")
    if el.cco_equiv:
        if not lines[-1].endswith(";"):
            lines[-1] += " ;"
        lines.append(f"    skos:closeMatch {el.cco_equiv}")
    if not lines[-1].endswith("."):
        lines[-1] += " ."
    lines.append("")
    return "\n".join(lines)


def _strip_leading_prefixes(body: str) -> str:
    lines = body.splitlines()
    while lines and (lines[0].startswith("@prefix") or lines[0].strip() == ""):
        lines.pop(0)
    # Drop leading schema-only comments before first triple when merging.
    while lines and lines[0].startswith("#"):
        lines.pop(0)
    while lines and lines[0].strip() == "":
        lines.pop(0)
    return "\n".join(lines).rstrip()


def write_modules_ontology() -> None:
    """Write the canonical modules/ ontology (owl:Ontology + schema + elements)."""
    if not SCHEMA_PATH.is_file():
        raise FileNotFoundError(f"Missing schema: {SCHEMA_PATH}")

    schema_body = _strip_leading_prefixes(SCHEMA_PATH.read_text(encoding="utf-8"))
    parts = [
        PREFIXES.rstrip(),
        "",
        ONTOLOGY_HEADER.rstrip(),
        "",
        "# Schema (from periodic_table/schema.ttl)",
        "",
        schema_body,
        "",
        "# Elements (from periodic_table/elements/; authoring fragments, not separate sidebar ontologies)",
        "",
    ]
    for path in sorted(ELEMENTS_DIR.glob("*.ttl")):
        parts.append(_strip_leading_prefixes(path.read_text(encoding="utf-8")))
        parts.append("")

    MODULES_ONTOLOGY_PATH.parent.mkdir(parents=True, exist_ok=True)
    MODULES_ONTOLOGY_PATH.write_text("\n".join(parts).rstrip() + "\n", encoding="utf-8")
    print(f"Wrote canonical modules ontology: {MODULES_ONTOLOGY_PATH}")


def main() -> None:
    ELEMENTS_DIR.mkdir(parents=True, exist_ok=True)
    for path in ELEMENTS_DIR.glob("*.ttl"):
        path.unlink()

    for el in ELEMENTS:
        filename = f"{el.number:03d}_{el.local_name}.ttl"
        (ELEMENTS_DIR / filename).write_text(render_element(el), encoding="utf-8")

    print(f"Generated {len(ELEMENTS)} element TTL fragments in {ELEMENTS_DIR}")
    write_modules_ontology()


if __name__ == "__main__":
    main()
