"""Generate portable DTOs and straightforward service methods; no runtime core import."""

import ast
import importlib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / "libs/naas-abi-sdk/naas_abi_sdk/services"
CORE = ROOT / "libs/naas-abi-core/naas_abi_core/services"
DOMAINS = {
    "object_storage": ("ObjectStorageService", ["ObjectMetaData"]),
    "activity_log": ("ActivityLogService", ["ActivityEvent", "ActivityLogQueryFilter"]),
    "coding_environment": (
        "CodingEnvironmentService",
        ["WorkspaceTemplate", "WorkspaceStatus", "WorkspaceAccess"],
    ),
    "source_control": (
        "SourceControlService",
        [
            "Repo",
            "ContentEntry",
            "FileContent",
            "Commit",
            "Branch",
            "DiffFile",
            "Diff",
            "Comment",
            "Review",
            "Check",
            "Proposal",
            "WorkflowRun",
            "MergeResult",
        ],
    ),
    "dataset": (
        "DatasetService",
        [
            "ColumnSpec",
            "PartitionSpec",
            "DatasetSpec",
            "DatasetInfo",
            "DatasetSnapshotInfo",
            "QueryResult",
        ],
    ),
    "email": ("EmailService", ["EmailAttachment"]),
    "vector_store": ("VectorStoreService", ["VectorDocument", "SearchResult"]),
    "event": ("EventService", ["StoredEvent"]),
}
models = """# Generated by tools/generate_services.py; do not edit.
from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any
"""
registry = []
for domain, (_, names) in DOMAINS.items():
    pb = importlib.import_module(f"naas_abi_proto.{domain}.v1.{domain}_pb2")
    for name in names:
        desc = pb.DESCRIPTOR.message_types_by_name[name]
        public = "ActivityLogQuery" if name == "ActivityLogQueryFilter" else name
        models += f"\n\n@dataclass\nclass {public}:\n"
        for f in desc.fields:
            if f.message_type:
                full = f.message_type.full_name
                typ = {
                    "google.protobuf.Timestamp": "datetime",
                    "google.protobuf.Struct": "dict[str, Any]",
                    "abi.vector_store.v1.VectorData": "list[float]",
                }.get(full, f.message_type.name)
            elif f.enum_type:
                typ = "str"
            else:
                typ = {
                    1: "float",
                    2: "float",
                    3: "int",
                    4: "int",
                    5: "int",
                    8: "bool",
                    9: "str",
                    12: "bytes",
                    13: "int",
                    17: "int",
                    18: "int",
                }.get(f.type, "Any")
            if f.is_repeated:
                typ = f"list[{typ}]"
                default = "field(default_factory=list)"
            elif f.has_presence:
                typ += " | None"
                default = "None"
            else:
                default = {
                    "str": '""',
                    "int": "0",
                    "float": "0.0",
                    "bool": "False",
                    "bytes": 'b""',
                }.get(typ, "None")
            if domain == "dataset" and f.name == "namespace":
                default = '"default"'
            if domain == "dataset" and name == "ColumnSpec" and f.name == "type":
                default = '"string"'
            if (
                domain == "dataset"
                and name == "PartitionSpec"
                and f.name == "transform"
            ):
                default = '"identity"'
            if (
                domain == "activity_log"
                and name == "ActivityEvent"
                and f.name == "timestamp"
            ):
                default = "field(default_factory=lambda: datetime.now(timezone.utc))"
            models += f"    {f.name}: {typ} = {default}\n"
        registry.append(f'    "{desc.full_name}": {public},')
models += (
    """

@dataclass
class FileWrite:
    path: str
    content: str | bytes


@dataclass
class FieldSpec:
    name: str
    type: str
    indexed: bool = False
    unique: bool = False


@dataclass
class CollectionSpec:
    name: str
    fields: tuple[FieldSpec, ...] = ()
    unique_together: tuple[tuple[str, ...], ...] = ()


@dataclass
class Document:
    id: str
    data: dict[str, Any]
    created_at: datetime
    updated_at: datetime
    version: int


@dataclass
class Page:
    items: list[Document]
    cursor: str | None


DTO_TYPES = {
"""
    + "\n".join(registry)
    + "\n}\n"
)
(OUT / "models.py").write_text(models)
# Handwritten facades cover compositional APIs; these signatures map directly to RPCs.
for domain in (
    "source_control",
    "coding_environment",
    "dataset",
    "activity_log",
    "email",
):
    cls, _ = DOMAINS[domain]
    tree = ast.parse((CORE / domain / f"{cls}.py").read_text())
    service = next(
        c for c in tree.body if isinstance(c, ast.ClassDef) and c.name == cls
    )
    pb = importlib.import_module(f"naas_abi_proto.{domain}.v1.{domain}_pb2")
    text = f'''# Generated by tools/generate_services.py; do not edit.
from __future__ import annotations
from typing import Any
from naas_abi_sdk.services._codec import ServiceProxy
from naas_abi_sdk.services.models import *  # noqa: F403 - generated DTO annotations


class {cls}(ServiceProxy):
    domain = "{domain}"
'''
    for m in service.body:
        if (
            not isinstance(m, ast.FunctionDef)
            or m.name.startswith("_")
            or m.name == "adapter"
        ):
            continue
        request_name = "".join(p.title() for p in m.name.split("_")) + "Request"
        if request_name not in pb.DESCRIPTOR.message_types_by_name:
            continue
        args = ast.unparse(m.args).replace("builtins.list", "list")
        args = args.replace("WriteMode", "str")
        returns = (
            ast.unparse(m.returns).replace("builtins.list", "list")
            if m.returns
            else "None"
        )
        values = [
            a.arg
            for a in [*m.args.posonlyargs, *m.args.args, *m.args.kwonlyargs]
            if a.arg != "self"
        ]
        text += f"\n    async def {m.name}({args}) -> {returns}:\n"
        text += (
            f'        return await self._request("{m.name}", '
            + ", ".join(f"{v}={v}" for v in values)
            + ")\n"
        )
    names = [
        node.name for node in ast.parse(models).body if isinstance(node, ast.ClassDef)
    ]
    used = [name for name in names if re.search(r"\b" + name + r"\b", text)]
    text = text.replace(
        "from naas_abi_sdk.services.models import *  # noqa: F403 - generated DTO annotations",
        "from naas_abi_sdk.services.models import " + ", ".join(used),
    )
    (OUT / f"_{domain}.py").write_text(text)
