"""DocumentsAgent internals: model policy, research gate, and title derivation."""

from naas_abi.agents.documents.policy import (
    DEFAULT_DOCUMENTS_MODEL,
    MAX_DOCUMENTS_SEARCHES,
    MAX_DOCUMENTS_SECTION_READS,
    apply_documents_model_override,
    attach_documents_research_note,
    bind_documents_reasoning,
    bind_documents_research_policy,
    configured_documents_model,
    documents_brief_requires_research,
    documents_creation_requested,
    documents_research_tools,
    documents_search_budget_remaining,
    documents_search_tool_bound,
    load_documents_chat_model,
    note_documents_list,
    note_documents_section_read,
    note_documents_web_search,
    reject_documents_section_read,
    reject_read_document,
    reject_repeat_list_document_sections,
    reject_repeat_apply_document_commands,
    reject_replace_in_document_on_fill,
    reject_unresearched_documents_write,
    resolve_documents_llm_model,
    validate_configured_documents_model,
)
from naas_abi.agents.documents.title import (
    auto_document_title,
    derive_document_title,
    is_placeholder_document_title,
    resolve_document_title,
)

__all__ = [
    "DEFAULT_DOCUMENTS_MODEL",
    "MAX_DOCUMENTS_SEARCHES",
    "MAX_DOCUMENTS_SECTION_READS",
    "apply_documents_model_override",
    "attach_documents_research_note",
    "auto_document_title",
    "bind_documents_reasoning",
    "bind_documents_research_policy",
    "configured_documents_model",
    "derive_document_title",
    "documents_brief_requires_research",
    "documents_creation_requested",
    "documents_research_tools",
    "documents_search_budget_remaining",
    "documents_search_tool_bound",
    "is_placeholder_document_title",
    "load_documents_chat_model",
    "note_documents_list",
    "note_documents_section_read",
    "note_documents_web_search",
    "reject_documents_section_read",
    "reject_read_document",
    "reject_repeat_list_document_sections",
    "reject_repeat_apply_document_commands",
    "reject_replace_in_document_on_fill",
    "reject_unresearched_documents_write",
    "resolve_document_title",
    "resolve_documents_llm_model",
    "validate_configured_documents_model",
]
