# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: naas_abi_proto/transfer/v1/transfer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'naas_abi_proto/transfer/v1/transfer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from naas_abi_proto.common.v1 import common_pb2 as naas__abi__proto_dot_common_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)naas_abi_proto/transfer/v1/transfer.proto\x12\x0f\x61\x62i.transfer.v1\x1a%naas_abi_proto/common/v1/common.proto\"t\n\x0bOpenRequest\x12+\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x1a.abi.common.v1.CallContext\x12\x11\n\toperation\x18\x02 \x01(\t\x12\x10\n\x08metadata\x18\x03 \x01(\x0c\x12\x13\n\x0b\x63hunk_bytes\x18\x04 \x01(\r\"X\n\x0cOpenResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x63hunk_bytes\x18\x02 \x01(\r\x12\'\n\x05\x65rror\x18\x0f \x01(\x0b\x32\x18.abi.common.v1.CallError\"g\n\x0cWriteRequest\x12+\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x1a.abi.common.v1.CallContext\x12\n\n\x02id\x18\x02 \x01(\t\x12\x10\n\x08sequence\x18\x03 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\"8\n\rWriteResponse\x12\'\n\x05\x65rror\x18\x0f \x01(\x0b\x32\x18.abi.common.v1.CallError\"G\n\x0cStartRequest\x12+\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x1a.abi.common.v1.CallContext\x12\n\n\x02id\x18\x02 \x01(\t\"8\n\rStartResponse\x12\'\n\x05\x65rror\x18\x0f \x01(\x0b\x32\x18.abi.common.v1.CallError\"X\n\x0bReadRequest\x12+\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x1a.abi.common.v1.CallContext\x12\n\n\x02id\x18\x02 \x01(\t\x12\x10\n\x08sequence\x18\x03 \x01(\x04\"\x89\x01\n\x0cReadResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x10\n\x08sequence\x18\x02 \x01(\x04\x12\x11\n\tframe_end\x18\x03 \x01(\x08\x12\x0f\n\x07pending\x18\x04 \x01(\x08\x12\x0c\n\x04\x64one\x18\x05 \x01(\x08\x12\'\n\x05\x65rror\x18\x0f \x01(\x0b\x32\x18.abi.common.v1.CallError\"G\n\x0c\x43loseRequest\x12+\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x1a.abi.common.v1.CallContext\x12\n\n\x02id\x18\x02 \x01(\t\"8\n\rCloseResponse\x12\'\n\x05\x65rror\x18\x0f \x01(\x0b\x32\x18.abi.common.v1.CallErrorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'naas_abi_proto.transfer.v1.transfer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPENREQUEST']._serialized_start=101
  _globals['_OPENREQUEST']._serialized_end=217
  _globals['_OPENRESPONSE']._serialized_start=219
  _globals['_OPENRESPONSE']._serialized_end=307
  _globals['_WRITEREQUEST']._serialized_start=309
  _globals['_WRITEREQUEST']._serialized_end=412
  _globals['_WRITERESPONSE']._serialized_start=414
  _globals['_WRITERESPONSE']._serialized_end=470
  _globals['_STARTREQUEST']._serialized_start=472
  _globals['_STARTREQUEST']._serialized_end=543
  _globals['_STARTRESPONSE']._serialized_start=545
  _globals['_STARTRESPONSE']._serialized_end=601
  _globals['_READREQUEST']._serialized_start=603
  _globals['_READREQUEST']._serialized_end=691
  _globals['_READRESPONSE']._serialized_start=694
  _globals['_READRESPONSE']._serialized_end=831
  _globals['_CLOSEREQUEST']._serialized_start=833
  _globals['_CLOSEREQUEST']._serialized_end=904
  _globals['_CLOSERESPONSE']._serialized_start=906
  _globals['_CLOSERESPONSE']._serialized_end=962
# @@protoc_insertion_point(module_scope)
