import importlib
import os

import click
import pydantic_core
import yaml
from naas_abi_core.engine.engine_configuration.EngineConfiguration import (
    EngineConfiguration,
)


@click.group("config")
def config():
    pass


# Every section of a config.yaml has a working default, so the scaffold writes
# only the one a project actually starts by editing — its modules — and
# documents the rest in comments. `abi config render` prints what a file
# resolves to once the defaults are filled in.
#
# Kept as a string rather than a template file on purpose: `config.yaml` is
# in the repo's .gitignore, so a template by that name is silently dropped
# from the built wheel unless it is force-included.
#
# Nothing below may contain Jinja expression syntax: the file is rendered as
# a template before it is parsed as YAML, so even a commented-out
# `{{ secret.NAME }}` resolves — and prompts — on the first load.
_MINIMAL_CONFIGURATION = """\
# ABI configuration, generated by `abi config init`.
#
# Every section is optional: anything left out falls back to an engine default,
# so this file only needs to say what your project changes. `abi config render`
# shows the fully resolved result, `abi config validate` checks it.
#
# Careful with secrets: this file is rendered as a Jinja template before it is
# parsed as YAML, so a `secret.NAME` reference in double braces resolves even
# inside a comment. Only write one where you really want the lookup.

# Modules to load, for example:
#   - module: naas_abi
#     enabled: true
# The engine always appends its own core modules (bfo, cco,
# templatablesparqlquery).
modules: []

# Left to the defaults, add a section only to change one:
#
#   api            HTTP API title, host and port (default 0.0.0.0:9879)
#   services       triple store, vector store, bus, kv, object storage, secrets
#   global_config  ai_mode (default "cloud") and public_api_host
#   default_agent  the agent `abi chat` opens (default "naas_abi AbiAgent")
#
# Secrets are read from ./.env unless a services.secret section says otherwise.
"""


@config.command("init")
@click.option(
    "--configuration-file",
    "-f",
    type=str,
    default="config.yaml",
    show_default=True,
    help="Path of the configuration file to write.",
)
@click.option(
    "--force",
    is_flag=True,
    default=False,
    help="Overwrite the configuration file if it already exists.",
)
def config_init(configuration_file: str, force: bool):
    """Write a default configuration file."""
    if os.path.exists(configuration_file) and not force:
        raise click.ClickException(
            f"{configuration_file} already exists. Re-run with --force to overwrite it."
        )

    directory = os.path.dirname(os.path.abspath(configuration_file))
    os.makedirs(directory, exist_ok=True)

    with open(configuration_file, "w") as file:
        file.write(_MINIMAL_CONFIGURATION)

    click.secho(f"Wrote {configuration_file}", fg="green")

    # The default secret service reads ./.env, so create it: an API key added
    # there is picked up with no further configuration. Beside the config file,
    # which is the directory the engine is normally run from.
    dotenv_path = os.path.join(directory, ".env")
    if not os.path.exists(dotenv_path):
        with open(dotenv_path, "w"):
            pass
        click.secho(
            f"Wrote {os.path.relpath(dotenv_path)} (secrets are read from here)",
            fg="green",
        )

    click.secho("Next: abi config validate", fg="bright_black")


def _validate_modules(configuration: EngineConfiguration) -> None:
    errors: list[str] = []

    for module_config in configuration.modules:
        if not module_config.enabled:
            continue

        if module_config.module is None:
            # path-based modules are not importable via importlib here; skip.
            continue

        module_name = module_config.module

        try:
            module = importlib.import_module(module_name)
        except Exception as e:  # noqa: BLE001
            errors.append(f"{module_name}: failed to import ({e})")
            continue

        if not hasattr(module, "ABIModule"):
            errors.append(f"{module_name}: missing ABIModule class")
            continue

        if not hasattr(module.ABIModule, "Configuration"):
            errors.append(f"{module_name}: ABIModule missing Configuration class")
            continue

        if not hasattr(module.ABIModule, "get_dependencies"):
            errors.append(f"{module_name}: ABIModule missing get_dependencies method")
            continue

        try:
            module.ABIModule.Configuration(
                global_config=configuration.global_config,
                **module_config.config,
            )
        except pydantic_core._pydantic_core.ValidationError as e:
            errors.append(f"{module_name}: invalid configuration ({e})")
            continue
        except Exception as e:  # noqa: BLE001
            errors.append(
                f"{module_name}: failed to instantiate Configuration ({e})"
            )
            continue

        print(f"  ✓ {module_name}")

    if errors:
        for err in errors:
            print(f"  ✗ {err}")
        raise click.ClickException(
            f"{len(errors)} module(s) failed validation"
        )


@config.command("validate")
@click.option("--configuration-file", type=str, required=False, default=None)
@click.option(
    "--modules",
    is_flag=True,
    default=False,
    help="Also validate that each enabled module is importable and its config is valid.",
)
def validate(configuration_file: str | None, modules: bool):
    configuration_content: str | None = None

    if configuration_file is not None:
        if not os.path.exists(configuration_file):
            raise FileNotFoundError(
                f"Configuration file {configuration_file} not found"
            )
        with open(configuration_file, "r") as file:
            configuration_content = file.read()

    configuration = EngineConfiguration.load_configuration(configuration_content)
    print("Configuration is valid")

    if modules:
        print("Validating modules...")
        _validate_modules(configuration)
        print("All enabled modules are valid")


@config.command("render")
@click.option("--configuration-file", type=str, required=False, default=None)
def render(configuration_file: str | None):
    configuration_content: str | None = None

    if configuration_file is not None:
        if not os.path.exists(configuration_file):
            raise FileNotFoundError(
                f"Configuration file {configuration_file} not found"
            )
        with open(configuration_file, "r") as file:
            configuration_content = file.read()

    configuration: EngineConfiguration = EngineConfiguration.load_configuration(
        configuration_content
    )
    print(yaml.dump(configuration.model_dump(), indent=2))
