integrations:
  version_control:
    - name: Gitlab
      description: Source code management and CI/CD platform
      type: DevOps
      category: Version Control & Collaboration
      website: https://gitlab.com
      documentation: https://docs.gitlab.com

  scheduling:
    - name: Acuity
      description: Appointment scheduling and business management software
      type: Business
      category: Scheduling & Calendar Management
      website: https://www.acuityscheduling.com
      documentation: https://help.acuityscheduling.com
    
    - name: Napta
      description: Resource planning and time management platform
      type: Business
      category: Resource Management & Scheduling
      website: https://www.napta.io
      documentation: https://help.napta.io

    - name: Akuiteo
      description: Professional services automation and resource management platform
      type: Business
      category: Resource Management & Scheduling
      website: https://www.akuiteo.com
      documentation: https://support.akuiteo.com

  microsoft_suite:
    - name: Microsoft Teams
      description: Communication and collaboration platform
      type: Communication
      category: Team Collaboration & Messaging
      website: https://www.microsoft.com/microsoft-teams
      documentation: https://learn.microsoft.com/microsoft-teams

    - name: SharePoint
      description: Document management and storage system
      type: Document Management
      category: Content Management & Storage
      website: https://www.microsoft.com/sharepoint
      documentation: https://learn.microsoft.com/sharepoint

    - name: PowerPoint
      description: Presentation software
      type: Productivity
      category: Content Creation & Presentation
      website: https://www.microsoft.com/powerpoint
      documentation: https://support.microsoft.com/powerpoint

    - name: Excel
      description: Spreadsheet software
      type: Productivity
      category: Data Analysis & Reporting
      website: https://www.microsoft.com/excel
      documentation: https://support.microsoft.com/excel

  cloud_platforms:
    - name: Azure
      description: Microsoft's cloud computing platform
      type: Cloud
      category: Cloud Infrastructure
      website: https://azure.microsoft.com
      documentation: https://learn.microsoft.com/azure

    - name: Google Cloud Platform
      description: Google's cloud computing services
      type: Cloud
      category: Cloud Infrastructure
      website: https://cloud.google.com
      documentation: https://cloud.google.com/docs

    - name: OpenStack
      description: Open-source cloud computing platform
      type: Cloud
      category: Cloud Infrastructure
      website: https://www.openstack.org
      documentation: https://docs.openstack.org

    - name: AWS
      description: Amazon Web Services cloud platform
      type: Cloud
      category: Cloud Infrastructure
      website: https://aws.amazon.com
      documentation: https://docs.aws.amazon.com

  data_science_tools:
    - name: Jupyter
      description: Interactive computing platform
      type: Development
      category: Data Science & Analytics
      website: https://jupyter.org
      documentation: https://docs.jupyter.org

    - name: Alteryx
      description: Data analytics automation platform
      type: Analytics
      category: Data Integration & Analytics
      website: https://www.alteryx.com
      documentation: https://help.alteryx.com

    - name: Dataiku
      description: Collaborative data science platform
      type: Analytics
      category: Data Science & ML Ops
      website: https://www.dataiku.com
      documentation: https://doc.dataiku.com

    - name: KNIME
      description: Open-source data analytics platform
      type: Analytics
      category: Data Integration & Analytics
      website: https://www.knime.com
      documentation: https://docs.knime.com

    - name: Data Galaxy
      description: Data governance and metadata management
      type: Data Management
      category: Data Governance
      website: https://www.datagalaxy.com
      documentation: https://help.datagalaxy.com

  visualization_tools:
    - name: Kibana
      description: Data visualization for Elasticsearch
      type: Visualization
      category: Data Visualization & Monitoring
      website: https://www.elastic.co/kibana
      documentation: https://www.elastic.co/guide/en/kibana

    - name: Grafana
      description: Analytics and monitoring solution
      type: Visualization
      category: Data Visualization & Monitoring
      website: https://grafana.com
      documentation: https://grafana.com/docs

    - name: Power BI
      description: Business analytics service
      type: Business Intelligence
      category: Data Visualization & Reporting
      website: https://powerbi.microsoft.com
      documentation: https://learn.microsoft.com/power-bi

    - name: Qlik
      description: Data analytics and visualization platform
      type: Business Intelligence
      category: Data Visualization & Reporting
      website: https://www.qlik.com
      documentation: https://help.qlik.com

    - name: Tableau
      description: Visual analytics platform
      type: Business Intelligence
      category: Data Visualization & Reporting
      website: https://www.tableau.com
      documentation: https://help.tableau.com

    - name: Plotly
      description: Interactive visualization library
      type: Development
      category: Data Visualization
      website: https://plotly.com
      documentation: https://plotly.com/python

    - name: D3.js
      description: JavaScript visualization library
      type: Development
      category: Data Visualization
      website: https://d3js.org
      documentation: https://github.com/d3/d3/wiki

  data_pipeline:
    - name: Apache Airflow
      description: Workflow management platform
      type: Orchestration
      category: Data Pipeline & Workflow
      website: https://airflow.apache.org
      documentation: https://airflow.apache.org/docs

    - name: Apache Kafka
      description: Distributed streaming platform
      type: Streaming
      category: Data Pipeline & Messaging
      website: https://kafka.apache.org
      documentation: https://kafka.apache.org/documentation

    - name: Quart
      description: Python web microframework
      type: Development
      category: Web Framework
      website: https://pgjones.gitlab.io/quart
      documentation: https://pgjones.gitlab.io/quart/tutorials

  databases:
    - name: Redis
      description: In-memory data structure store
      type: Database
      category: NoSQL Database
      website: https://redis.io
      documentation: https://redis.io/documentation

    - name: MongoDB
      description: Document-oriented database
      type: Database
      category: NoSQL Database
      website: https://www.mongodb.com
      documentation: https://docs.mongodb.com

    - name: Apache Spark
      description: Unified analytics engine
      type: Processing
      category: Big Data Processing
      website: https://spark.apache.org
      documentation: https://spark.apache.org/docs

    - name: Delta Lake
      description: Storage layer for data lakes
      type: Storage
      category: Data Lake
      website: https://delta.io
      documentation: https://docs.delta.io

    - name: Snowflake
      description: Cloud data platform
      type: Data Warehouse
      category: Cloud Data Platform
      website: https://www.snowflake.com
      documentation: https://docs.snowflake.com

    - name: Elasticsearch
      description: Search and analytics engine
      type: Search
      category: Search & Analytics
      website: https://www.elastic.co/elasticsearch
      documentation: https://www.elastic.co/guide/en/elasticsearch

    - name: MySQL
      description: Relational database management system
      type: Database
      category: Relational Database
      website: https://www.mysql.com
      documentation: https://dev.mysql.com/doc

    - name: Cassandra
      description: Distributed NoSQL database
      type: Database
      category: NoSQL Database
      website: https://cassandra.apache.org
      documentation: https://cassandra.apache.org/doc