"""Endpoint resolution has to be right on macOS, Linux and WSL, but CI runs on
one of them. Every platform signal is therefore injectable, so all three paths
are exercised from any machine."""

from __future__ import annotations

from naas_abi_marketplace.ai.ollama.endpoint import (
    BASE_URL_ENV_VAR,
    DEFAULT_BASE_URL,
    OLLAMA_HOST_ENV_VAR,
    candidate_base_urls,
    find_ollama_binary,
    install_hint,
    is_wsl,
    normalize_base_url,
    resolve_base_url,
    wsl_host_addresses,
)

# --------------------------------------------------------------- normalization


def test_normalize_passes_through_a_full_url() -> None:
    assert normalize_base_url("http://localhost:11434") == "http://localhost:11434"


def test_normalize_adds_scheme_and_port_to_a_bare_host() -> None:
    assert normalize_base_url("192.168.1.10") == "http://192.168.1.10:11434"


def test_normalize_adds_scheme_to_host_port() -> None:
    assert normalize_base_url("127.0.0.1:1234") == "http://127.0.0.1:1234"


def test_normalize_accepts_a_bare_port_like_ollama_does() -> None:
    assert normalize_base_url("11434") == "http://localhost:11434"


def test_normalize_maps_wildcard_bind_to_a_dialable_host() -> None:
    """OLLAMA_HOST=0.0.0.0 means "listen everywhere", not "connect here"."""
    assert normalize_base_url("0.0.0.0:11434") == "http://localhost:11434"


def test_normalize_keeps_https() -> None:
    assert normalize_base_url("https://ollama.internal") == (
        "https://ollama.internal:11434"
    )


def test_normalize_handles_bracketed_ipv6_with_port() -> None:
    assert normalize_base_url("[::1]:11434") == "http://[::1]:11434"


def test_normalize_falls_back_on_empty_input() -> None:
    assert normalize_base_url("   ") == DEFAULT_BASE_URL


# ------------------------------------------------------------- WSL detection


def test_is_wsl_true_from_env_marker() -> None:
    assert is_wsl(environ={"WSL_DISTRO_NAME": "Ubuntu"}, proc_version_path="/nope")


def test_is_wsl_true_from_proc_version(tmp_path) -> None:
    proc_version = tmp_path / "version"
    proc_version.write_text(
        "Linux version 5.15.0-microsoft-standard-WSL2 (gcc ...)", encoding="utf-8"
    )
    assert is_wsl(environ={}, proc_version_path=str(proc_version))


def test_is_wsl_false_on_plain_linux(tmp_path) -> None:
    proc_version = tmp_path / "version"
    proc_version.write_text("Linux version 6.8.0-45-generic (gcc ...)", encoding="utf-8")
    assert not is_wsl(environ={}, proc_version_path=str(proc_version))


def test_is_wsl_false_when_proc_version_is_absent() -> None:
    """macOS has no /proc/version — absence must not raise."""
    assert not is_wsl(environ={}, proc_version_path="/does/not/exist")


# ------------------------------------------------------- WSL host discovery


def test_wsl_host_addresses_reads_nameserver(tmp_path) -> None:
    resolv = tmp_path / "resolv.conf"
    resolv.write_text(
        "# generated by WSL\nnameserver 172.29.160.1\nsearch example.com\n",
        encoding="utf-8",
    )
    assert wsl_host_addresses(str(resolv)) == ["172.29.160.1", "host.docker.internal"]


def test_wsl_host_addresses_survives_a_missing_file() -> None:
    assert wsl_host_addresses("/does/not/exist") == ["host.docker.internal"]


# ------------------------------------------------------------ candidate order


def test_candidates_on_macos_are_just_loopback() -> None:
    assert candidate_base_urls(environ={}, wsl=False) == [DEFAULT_BASE_URL]


def test_configured_value_wins_over_everything() -> None:
    candidates = candidate_base_urls(
        "http://ollama.box:9999",
        environ={
            BASE_URL_ENV_VAR: "http://abi-override:11434",
            OLLAMA_HOST_ENV_VAR: "http://ollama-host:11434",
        },
        wsl=False,
    )
    assert candidates[0] == "http://ollama.box:9999"


def test_abi_override_beats_ollama_host() -> None:
    candidates = candidate_base_urls(
        environ={
            BASE_URL_ENV_VAR: "http://abi-override:11434",
            OLLAMA_HOST_ENV_VAR: "http://ollama-host:11434",
        },
        wsl=False,
    )
    assert candidates[:2] == [
        "http://abi-override:11434",
        "http://ollama-host:11434",
    ]


def test_ollama_host_is_honoured() -> None:
    candidates = candidate_base_urls(
        environ={OLLAMA_HOST_ENV_VAR: "10.0.0.5:11434"}, wsl=False
    )
    assert candidates[0] == "http://10.0.0.5:11434"


def test_wsl_appends_windows_host_after_loopback(tmp_path) -> None:
    """Ollama inside the distro must win; the Windows app is the fallback."""
    resolv = tmp_path / "resolv.conf"
    resolv.write_text("nameserver 172.29.160.1\n", encoding="utf-8")

    candidates = candidate_base_urls(
        environ={}, wsl=True, resolv_conf_path=str(resolv)
    )
    assert candidates == [
        DEFAULT_BASE_URL,
        "http://172.29.160.1:11434",
        "http://host.docker.internal:11434",
    ]


def test_candidates_are_deduplicated() -> None:
    candidates = candidate_base_urls(
        "http://localhost:11434",
        environ={OLLAMA_HOST_ENV_VAR: "localhost:11434"},
        wsl=False,
    )
    assert candidates == [DEFAULT_BASE_URL]


# ------------------------------------------------------------------ resolution


def test_resolve_picks_the_first_candidate_that_answers(monkeypatch, tmp_path) -> None:
    resolv = tmp_path / "resolv.conf"
    resolv.write_text("nameserver 172.29.160.1\n", encoding="utf-8")

    # Simulate WSL with the Ollama Windows app on the host: loopback is dead,
    # the nameserver address answers.
    reachable = "http://172.29.160.1:11434"
    monkeypatch.setattr(
        "naas_abi_marketplace.ai.ollama.endpoint.probe_base_url",
        lambda url, timeout=0.75: url == reachable,
    )

    base_url, ok = resolve_base_url(
        environ={}, wsl=True, resolv_conf_path=str(resolv)
    )
    assert (base_url, ok) == (reachable, True)


def test_resolve_reports_unreachable_without_raising(monkeypatch) -> None:
    """A project must boot with ollama down — the error belongs at first use."""
    monkeypatch.setattr(
        "naas_abi_marketplace.ai.ollama.endpoint.probe_base_url",
        lambda url, timeout=0.75: False,
    )
    base_url, ok = resolve_base_url(environ={}, wsl=False)
    assert (base_url, ok) == (DEFAULT_BASE_URL, False)


def test_resolve_can_skip_probing_entirely() -> None:
    base_url, ok = resolve_base_url(
        "http://ollama.box:11434", environ={}, wsl=False, probe=False
    )
    assert (base_url, ok) == ("http://ollama.box:11434", False)


# --------------------------------------------------------------- binary lookup


def test_find_binary_checks_macos_app_bundle(monkeypatch) -> None:
    monkeypatch.setattr(
        "naas_abi_marketplace.ai.ollama.endpoint.shutil.which", lambda _: None
    )
    app_path = "/Applications/Ollama.app/Contents/Resources/ollama"
    assert (
        find_ollama_binary(system="Darwin", path_exists=lambda p: p == app_path)
        == app_path
    )


def test_find_binary_checks_linux_paths(monkeypatch) -> None:
    monkeypatch.setattr(
        "naas_abi_marketplace.ai.ollama.endpoint.shutil.which", lambda _: None
    )
    assert (
        find_ollama_binary(system="Linux", path_exists=lambda p: p == "/usr/bin/ollama")
        == "/usr/bin/ollama"
    )


def test_find_binary_returns_none_when_absent(monkeypatch) -> None:
    monkeypatch.setattr(
        "naas_abi_marketplace.ai.ollama.endpoint.shutil.which", lambda _: None
    )
    assert find_ollama_binary(system="Linux", path_exists=lambda _: False) is None


# ------------------------------------------------------------------- hints


def test_hint_mentions_brew_on_macos() -> None:
    assert "brew" in install_hint(system="Darwin", wsl=False)


def test_hint_mentions_systemd_on_linux() -> None:
    assert "systemctl" in install_hint(system="Linux", wsl=False)


def test_wsl_hint_explains_the_host_boundary() -> None:
    """The usual WSL failure is a reachability problem, not a missing install."""
    hint = install_hint(system="Linux", wsl=True)
    assert "WSL" in hint
    assert "OLLAMA_HOST=0.0.0.0" in hint
    assert BASE_URL_ENV_VAR in hint


def test_wsl_hint_wins_over_the_linux_hint() -> None:
    """WSL reports itself as Linux, so the WSL branch must be checked first."""
    assert install_hint(system="Linux", wsl=True) != install_hint(
        system="Linux", wsl=False
    )


def test_native_windows_is_pointed_at_wsl() -> None:
    assert "WSL" in install_hint(system="Windows", wsl=False)
