import os
import re
import tempfile
from dataclasses import dataclass
from typing import Annotated

from docling.datamodel.base_models import InputFormat
from docling.datamodel.pipeline_options import (
    PdfPipelineOptions,
    PictureDescriptionApiOptions,
)
from docling.document_converter import DocumentConverter, PdfFormatOption
from docling_core.transforms.serializer.html import HTMLDocSerializer, HTMLParams
from docling_core.types.doc import ImageRefMode
from naas_abi_marketplace.domains.document import ABIModule
from naas_abi_marketplace.domains.document.ontologies.classes.ontology_naas_ai.abi.document.File import (
    File,
)
from naas_abi_marketplace.domains.document.pipelines.ConvertFileBasePipeline import (
    ConvertFileBasePipeline,
    ConvertFileBasePipelineConfiguration,
    ConvertFileBasePipelineParameters,
)
from pydantic import Field

_BODY_RE = re.compile(r"<body[^>]*>(.*?)</body>", re.DOTALL)


@dataclass
class PdfToHtmlPipelineConfiguration(ConvertFileBasePipelineConfiguration):
    """Configuration for PdfToHtmlPipeline.

    When ``image_description_api_key`` is set, docling calls a vision-capable
    LLM (via any OpenAI-compatible endpoint) for each picture in the PDF and
    embeds the description as a ``<figcaption>`` in the exported HTML.
    """

    mime_type: Annotated[
        str,
        Field(description="The MIME type of the files to convert to HTML."),
    ] = "application/pdf"
    output_mime_type: Annotated[
        str,
        Field(description="The MIME type of the converted output files."),
    ] = "text/html"
    output_extension: Annotated[
        str,
        Field(description="The file extension appended to converted files."),
    ] = ".html"
    images_scale: Annotated[
        float,
        Field(description="Resolution scale for embedded images (1.0 = native)."),
    ] = 2.0
    # Optional vision-LLM image captioning
    image_description_api_key: Annotated[
        str,
        Field(description="API key for the vision endpoint. Empty disables captioning."),
    ] = ""
    image_description_base_url: Annotated[
        str,
        Field(description="OpenAI-compatible chat completions endpoint URL."),
    ] = "https://openrouter.ai/api/v1/chat/completions"
    image_description_model: Annotated[
        str,
        Field(description="Vision model identifier (e.g. 'google/gemini-2.0-flash-001')."),
    ] = "google/gemini-2.0-flash-001"
    image_description_prompt: Annotated[
        str,
        Field(description="Prompt sent to the vision model for each image."),
    ] = (
        "Describe this image in one or two sentences, focusing on factual "
        "content that would be useful for document understanding (people, "
        "charts, tables, diagrams, scenes). Be concise and factual."
    )
    image_description_concurrency: Annotated[
        int,
        Field(description="Number of parallel vision-API calls."),
    ] = 4
    image_description_timeout_seconds: Annotated[
        float,
        Field(description="Per-call timeout for the vision endpoint."),
    ] = 30.0
    image_description_picture_area_threshold: Annotated[
        float,
        Field(description="Skip pictures whose area is below this fraction of the page."),
    ] = 0.05


class PdfToHtmlPipelineParameters(ConvertFileBasePipelineParameters):
    processor_iri: Annotated[
        str,
        Field(description="The IRI of the file ingestion processor."),
    ] = "http://ontology.naas.ai/abi/document/PDFToHTMLProcessor"


class PdfToHtmlPipeline(ConvertFileBasePipeline):
    """Pipeline converting PDF files to structured HTML using docling.

    The output is a single self-contained HTML document with embedded images.
    Each PDF page is wrapped in a ``<section class="pdf-page" data-page="N">``
    block so downstream chunkers can attach page-level metadata to each chunk.
    When configured, picture descriptions generated by a vision LLM are
    written into ``<figcaption>`` elements in the same pass.
    """

    module: ABIModule
    __pipeline_options: PdfPipelineOptions

    def __init__(self, configuration: PdfToHtmlPipelineConfiguration):
        super().__init__(configuration)
        self.module = ABIModule.get_instance()
        self.__pipeline_options = self._build_pipeline_options(configuration)

    @staticmethod
    def _build_pipeline_options(
        configuration: PdfToHtmlPipelineConfiguration,
    ) -> PdfPipelineOptions:
        opts = PdfPipelineOptions()
        opts.generate_picture_images = True
        opts.images_scale = configuration.images_scale

        if configuration.image_description_api_key:
            opts.do_picture_description = True
            opts.picture_description_options = PictureDescriptionApiOptions(
                url=configuration.image_description_base_url,
                headers={
                    "Authorization": f"Bearer {configuration.image_description_api_key}",
                },
                params={"model": configuration.image_description_model},
                prompt=configuration.image_description_prompt,
                concurrency=configuration.image_description_concurrency,
                timeout=configuration.image_description_timeout_seconds,
                picture_area_threshold=configuration.image_description_picture_area_threshold,
            )
            # Docling requires explicit opt-in for remote services.
            opts.enable_remote_services = True

        return opts

    def _build_converter(self) -> DocumentConverter:
        return DocumentConverter(
            format_options={
                InputFormat.PDF: PdfFormatOption(
                    pipeline_options=self.__pipeline_options
                )
            }
        )

    def convert(self, file: File) -> str:
        content = file.read()

        # docling expects a path; write to a temp file.
        with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as tmp:
            tmp.write(content)
            tmp_path = tmp.name
        try:
            result = self._build_converter().convert(tmp_path)
        finally:
            os.unlink(tmp_path)

        doc = result.document
        sections: list[str] = []
        for page_no in sorted(doc.pages.keys()):
            params = HTMLParams(
                pages={page_no},
                image_mode=ImageRefMode.EMBEDDED,
            )
            page_html = HTMLDocSerializer(doc=doc, params=params).serialize().text
            match = _BODY_RE.search(page_html)
            inner = match.group(1) if match else page_html
            sections.append(
                f'<section class="pdf-page" data-page="{page_no}">\n{inner}\n</section>'
            )

        title = file.file_name
        return (
            "<!DOCTYPE html>\n"
            '<html lang="fr">\n'
            "<head>\n"
            '<meta charset="utf-8" />\n'
            f"<title>{title}</title>\n"
            "</head>\n"
            "<body>\n"
            + "\n".join(sections)
            + "\n</body>\n</html>\n"
        )
