"""Generate explicit typed request/response clients from the v1 message pairs."""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
PROTO = ROOT / "libs/naas-abi-proto/naas_abi_proto"
SDK = ROOT / "libs/naas-abi-sdk/naas_abi_sdk"


def snake(name):
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


imports = []
initializers = []
catalog = {}
for file in sorted(PROTO.glob("*/v1/*.proto")):
    domain = file.stem
    if domain == "common":
        continue
    cls = "".join(p.title() for p in domain.split("_")) + "Client"
    methods = re.findall(r"message (\w+)Request \{", file.read_text())
    catalog[domain] = [snake(n) for n in methods]
    text = f"""# Generated by naas-abi-proto/tools/generate_clients.py; do not edit.
from naas_abi_proto.{domain}.v1 import {domain}_pb2 as pb
from naas_abi_sdk.transport import Transport


class {cls}:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport
"""
    for name in methods:
        method = snake(name)
        text += f"""
    async def {method}(self, request: pb.{name}Request) -> pb.{name}Response:
        return await self._transport.call("abi.svc.{domain}.v1.{method}", request, pb.{name}Response)
"""
    if domain == "cache":
        text = text.replace(
            "def __init__(self, transport: Transport) -> None:",
            'def __init__(self, transport: Transport, *, subject_prefix: str = "abi.svc.cache.v1") -> None:',
        )
        text = text.replace(
            "        self._transport = transport",
            "        self._transport = transport\n        self._subject_prefix = subject_prefix",
        )
        text = text.replace('"abi.svc.cache.v1.', 'f"{self._subject_prefix}.')
        text += '''
    def tier(self, index: int) -> "CacheClient":
        """Select an explicitly configured tier by its order in cache.adapters."""
        if index < 0:
            raise ValueError("tier index must be nonnegative")
        return CacheClient(self._transport, subject_prefix=f"abi.svc.cache.v1.tier.{index}")
'''
    if domain == "document":
        text = text.replace("def __init__(self, transport: Transport) -> None:", "def __init__(self, transport: Transport, namespace: str | None = None) -> None:")
        text = text.replace("        self._transport = transport", "        self._transport = transport\n        self._namespace = namespace")
        text = text.replace(", request, pb.", ", self._scoped(request), pb.")
        text += '''
    def for_namespace(self, namespace: str) -> "DocumentClient":
        if self._namespace is not None and namespace != self._namespace:
            raise ValueError("A bound document client cannot change namespace")
        if not namespace or "\\x00" in namespace:
            raise ValueError("A module namespace is required")
        return DocumentClient(self._transport, namespace)

    def _scoped(self, request):
        if self._namespace is None:
            return request
        if request.namespace and request.namespace != self._namespace:
            raise ValueError("Request does not match the module namespace")
        cloned = type(request)()
        cloned.CopyFrom(request)
        cloned.namespace = self._namespace
        return cloned
'''
    (SDK / f"{domain}.py").write_text(text)
    imports.append(f"from naas_abi_sdk.{domain} import {cls}")
    initializers.append(f"        self.{domain} = {cls}(self._transport)")
(SDK / "client.py").write_text(
    '''"""Typed engine services sharing one NATS connection."""
from __future__ import annotations
from collections.abc import Callable
from typing import Any
from naas_abi_sdk.transport import Transport
from naas_abi_sdk.bus import BusClient
'''
    + "\n".join(imports)
    + """


class ABIClient:
    def __init__(self, url: str, token: str | Callable[[], str], *, timeout: float = 10.0, **connection_options: Any) -> None:
        self._transport = Transport(url, token, timeout, **connection_options)
        self.bus = BusClient(self._transport)
"""
    + "\n".join(initializers)
    + '''

    async def __aenter__(self) -> ABIClient:  # noqa: PYI034 - Python 3.10 without typing_extensions
        return self

    async def __aexit__(self, *exc) -> None:
        await self.close()

    async def close(self) -> None:
        """Release this client's connection; never shut down a remote service."""
        await self._transport.close()
'''
)
(SDK / "catalog.py").write_text(
    '"""Generated inventory of the supported RPC surface."""\nOPERATIONS = '
    + repr(catalog)
    + "\n"
)
