# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: naas_abi_proto/email/v1/email.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'naas_abi_proto/email/v1/email.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from naas_abi_proto.common.v1 import common_pb2 as naas__abi__proto_dot_common_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#naas_abi_proto/email/v1/email.proto\x12\x0c\x61\x62i.email.v1\x1a%naas_abi_proto/common/v1/common.proto\"\x82\x01\n\x0f\x45mailAttachment\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\x12\x11\n\tmime_type\x18\x03 \x01(\t\x12\x17\n\ncontent_id\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x11\n\tis_inline\x18\x05 \x01(\x08\x42\r\n\x0b_content_id\"\xe0\x02\n\x0bSendRequest\x12+\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x1a.abi.common.v1.CallContext\x12\x15\n\x08to_email\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x0f\n\x07subject\x18\x03 \x01(\t\x12\x11\n\ttext_body\x18\x04 \x01(\t\x12\x16\n\thtml_body\x18\x05 \x01(\tH\x01\x88\x01\x01\x12\x12\n\nfrom_email\x18\x06 \x01(\t\x12\x16\n\tfrom_name\x18\x07 \x01(\tH\x02\x88\x01\x01\x12\x15\n\x08reply_to\x18\x08 \x01(\tH\x03\x88\x01\x01\x12\x32\n\x0b\x61ttachments\x18\t \x03(\x0b\x32\x1d.abi.email.v1.EmailAttachment\x12\x11\n\tto_emails\x18\n \x03(\t\x12\x11\n\tcc_emails\x18\x0b \x03(\tB\x0b\n\t_to_emailB\x0c\n\n_html_bodyB\x0c\n\n_from_nameB\x0b\n\t_reply_to\"F\n\x0cSendResponse\x12,\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x18.abi.common.v1.CallErrorH\x00\x88\x01\x01\x42\x08\n\x06_errorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'naas_abi_proto.email.v1.email_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMAILATTACHMENT']._serialized_start=93
  _globals['_EMAILATTACHMENT']._serialized_end=223
  _globals['_SENDREQUEST']._serialized_start=226
  _globals['_SENDREQUEST']._serialized_end=578
  _globals['_SENDRESPONSE']._serialized_start=580
  _globals['_SENDRESPONSE']._serialized_end=650
# @@protoc_insertion_point(module_scope)
