# Generated by naas-abi-proto/tools/generate_clients.py; do not edit.
from naas_abi_proto.activity_log.v1 import activity_log_pb2 as pb

from naas_abi_sdk.transport import Transport


class ActivityLogClient:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    async def record(self, request: pb.RecordRequest) -> pb.RecordResponse:
        return await self._transport.call(
            "abi.svc.activity_log.v1.record", request, pb.RecordResponse
        )

    async def query(self, request: pb.QueryRequest) -> pb.QueryResponse:
        return await self._transport.call(
            "abi.svc.activity_log.v1.query", request, pb.QueryResponse
        )

    async def list_actors(self, request: pb.ListActorsRequest) -> pb.ListActorsResponse:
        return await self._transport.call(
            "abi.svc.activity_log.v1.list_actors", request, pb.ListActorsResponse
        )

    async def shutdown(self, request: pb.ShutdownRequest) -> pb.ShutdownResponse:
        return await self._transport.call(
            "abi.svc.activity_log.v1.shutdown", request, pb.ShutdownResponse
        )
