# Generated by naas-abi-proto/tools/generate_clients.py; do not edit.
from naas_abi_proto.cache.v1 import cache_pb2 as pb

from naas_abi_sdk.transport import Transport


class CacheClient:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    async def get(self, request: pb.GetRequest) -> pb.GetResponse:
        return await self._transport.call(
            "abi.svc.cache.v1.get", request, pb.GetResponse
        )

    async def set(self, request: pb.SetRequest) -> pb.SetResponse:
        return await self._transport.call(
            "abi.svc.cache.v1.set", request, pb.SetResponse
        )

    async def set_if_absent(
        self, request: pb.SetIfAbsentRequest
    ) -> pb.SetIfAbsentResponse:
        return await self._transport.call(
            "abi.svc.cache.v1.set_if_absent", request, pb.SetIfAbsentResponse
        )

    async def delete(self, request: pb.DeleteRequest) -> pb.DeleteResponse:
        return await self._transport.call(
            "abi.svc.cache.v1.delete", request, pb.DeleteResponse
        )

    async def exists(self, request: pb.ExistsRequest) -> pb.ExistsResponse:
        return await self._transport.call(
            "abi.svc.cache.v1.exists", request, pb.ExistsResponse
        )
