"""Generated inventory of the supported RPC surface."""

OPERATIONS = {
    "activity_log": ["record", "query", "list_actors", "shutdown"],
    "cache": ["get", "set", "set_if_absent", "delete", "exists"],
    "coding_environment": [
        "ensure_user",
        "list_templates",
        "provision",
        "start",
        "stop",
        "delete",
        "list_environments",
        "get_status",
        "get_logs",
        "get_access",
    ],
    "dataset": [
        "create",
        "describe",
        "list",
        "write",
        "query",
        "flush",
        "inlined_row_count",
        "compact",
        "list_snapshots",
        "drop",
    ],
    "email": ["send"],
    "event": [
        "append",
        "query",
        "max_seq",
        "get_cursor",
        "set_cursor",
        "query_for_consumer",
    ],
    "keyvalue": [
        "get",
        "set",
        "set_if_not_exists",
        "delete",
        "delete_if_value_matches",
        "exists",
    ],
    "object_storage": [
        "get_object",
        "put_object",
        "delete_object",
        "list_objects",
        "list_objects_recursive",
        "get_object_metadata",
    ],
    "secret": ["get", "set", "remove", "list"],
    "source_control": [
        "ensure_user",
        "ensure_repo",
        "list_repos",
        "add_collaborator",
        "list_contents",
        "get_file",
        "upsert_file",
        "upsert_files",
        "list_commits",
        "list_branches",
        "create_branch",
        "delete_branch",
        "get_diff",
        "create_proposal",
        "list_proposals",
        "get_proposal",
        "get_proposal_diff",
        "list_proposal_commits",
        "list_comments",
        "list_reviews",
        "add_comment",
        "submit_review",
        "list_checks",
        "set_branch_protection",
        "merge",
        "list_workflow_runs",
        "mint_git_token",
    ],
    "triple_store": [
        "insert",
        "remove",
        "get",
        "handle_view_event",
        "query",
        "query_view",
        "get_subject_graph",
        "create_graph",
        "clear_graph",
        "drop_graph",
        "list_graphs",
    ],
    "vector_store": [
        "initialize",
        "create_collection",
        "delete_collection",
        "list_collections",
        "store_vectors",
        "search",
        "get_vector",
        "update_vector",
        "delete_vectors",
        "count_vectors",
        "close",
    ],
}
