# Generated by naas-abi-proto/tools/generate_clients.py; do not edit.
from naas_abi_proto.coding_environment.v1 import coding_environment_pb2 as pb

from naas_abi_sdk.transport import Transport


class CodingEnvironmentClient:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    async def ensure_user(self, request: pb.EnsureUserRequest) -> pb.EnsureUserResponse:
        return await self._transport.call(
            "abi.svc.coding_environment.v1.ensure_user", request, pb.EnsureUserResponse
        )

    async def list_templates(
        self, request: pb.ListTemplatesRequest
    ) -> pb.ListTemplatesResponse:
        return await self._transport.call(
            "abi.svc.coding_environment.v1.list_templates",
            request,
            pb.ListTemplatesResponse,
        )

    async def provision(self, request: pb.ProvisionRequest) -> pb.ProvisionResponse:
        return await self._transport.call(
            "abi.svc.coding_environment.v1.provision", request, pb.ProvisionResponse
        )

    async def start(self, request: pb.StartRequest) -> pb.StartResponse:
        return await self._transport.call(
            "abi.svc.coding_environment.v1.start", request, pb.StartResponse
        )

    async def stop(self, request: pb.StopRequest) -> pb.StopResponse:
        return await self._transport.call(
            "abi.svc.coding_environment.v1.stop", request, pb.StopResponse
        )

    async def delete(self, request: pb.DeleteRequest) -> pb.DeleteResponse:
        return await self._transport.call(
            "abi.svc.coding_environment.v1.delete", request, pb.DeleteResponse
        )

    async def list_environments(
        self, request: pb.ListEnvironmentsRequest
    ) -> pb.ListEnvironmentsResponse:
        return await self._transport.call(
            "abi.svc.coding_environment.v1.list_environments",
            request,
            pb.ListEnvironmentsResponse,
        )

    async def get_status(self, request: pb.GetStatusRequest) -> pb.GetStatusResponse:
        return await self._transport.call(
            "abi.svc.coding_environment.v1.get_status", request, pb.GetStatusResponse
        )

    async def get_logs(self, request: pb.GetLogsRequest) -> pb.GetLogsResponse:
        return await self._transport.call(
            "abi.svc.coding_environment.v1.get_logs", request, pb.GetLogsResponse
        )

    async def get_access(self, request: pb.GetAccessRequest) -> pb.GetAccessResponse:
        return await self._transport.call(
            "abi.svc.coding_environment.v1.get_access", request, pb.GetAccessResponse
        )
