# Generated by naas-abi-proto/tools/generate_clients.py; do not edit.
from naas_abi_proto.document.v1 import document_pb2 as pb

from naas_abi_sdk.transport import Transport


class DocumentClient:
    def __init__(self, transport: Transport, namespace: str | None = None) -> None:
        self._transport = transport
        self._namespace = namespace

    async def ensure_collection(
        self, request: pb.EnsureCollectionRequest
    ) -> pb.EnsureCollectionResponse:
        return await self._transport.call(
            "abi.svc.document.v1.ensure_collection",
            self._scoped(request),
            pb.EnsureCollectionResponse,
        )

    async def drop_collection(
        self, request: pb.DropCollectionRequest
    ) -> pb.DropCollectionResponse:
        return await self._transport.call(
            "abi.svc.document.v1.drop_collection",
            self._scoped(request),
            pb.DropCollectionResponse,
        )

    async def collections(
        self, request: pb.CollectionsRequest
    ) -> pb.CollectionsResponse:
        return await self._transport.call(
            "abi.svc.document.v1.collections",
            self._scoped(request),
            pb.CollectionsResponse,
        )

    async def put(self, request: pb.PutRequest) -> pb.PutResponse:
        return await self._transport.call(
            "abi.svc.document.v1.put", self._scoped(request), pb.PutResponse
        )

    async def get(self, request: pb.GetRequest) -> pb.GetResponse:
        return await self._transport.call(
            "abi.svc.document.v1.get", self._scoped(request), pb.GetResponse
        )

    async def delete(self, request: pb.DeleteRequest) -> pb.DeleteResponse:
        return await self._transport.call(
            "abi.svc.document.v1.delete", self._scoped(request), pb.DeleteResponse
        )

    async def find(self, request: pb.FindRequest) -> pb.FindResponse:
        return await self._transport.call(
            "abi.svc.document.v1.find", self._scoped(request), pb.FindResponse
        )

    async def count(self, request: pb.CountRequest) -> pb.CountResponse:
        return await self._transport.call(
            "abi.svc.document.v1.count", self._scoped(request), pb.CountResponse
        )

    def for_namespace(self, namespace: str) -> "DocumentClient":
        if self._namespace is not None and namespace != self._namespace:
            raise ValueError("A bound document client cannot change namespace")
        if not namespace or "\x00" in namespace:
            raise ValueError("A module namespace is required")
        return DocumentClient(self._transport, namespace)

    def _scoped(self, request):
        if self._namespace is None:
            return request
        if request.namespace and request.namespace != self._namespace:
            raise ValueError("Request does not match the module namespace")
        cloned = type(request)()
        cloned.CopyFrom(request)
        cloned.namespace = self._namespace
        return cloned
