# Generated by naas-abi-proto/tools/generate_clients.py; do not edit.
from naas_abi_proto.email.v1 import email_pb2 as pb

from naas_abi_sdk.transport import Transport


class EmailClient:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    async def send(self, request: pb.SendRequest) -> pb.SendResponse:
        return await self._transport.call(
            "abi.svc.email.v1.send", request, pb.SendResponse
        )
