# Generated by naas-abi-proto/tools/generate_clients.py; do not edit.
from naas_abi_proto.email.v1 import email_pb2 as pb

from naas_abi_sdk.transport import Transport


class EmailClient:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    async def send(self, request: pb.SendRequest) -> pb.SendResponse:
        return await self._transport.call(
            "abi.svc.email.v1.send", request, pb.SendResponse
        )

    async def list_sent(self, request: pb.ListSentRequest) -> pb.ListSentResponse:
        return await self._transport.call(
            "abi.svc.email.v1.list_sent", request, pb.ListSentResponse
        )

    async def get_sent(self, request: pb.GetSentRequest) -> pb.GetSentResponse:
        return await self._transport.call(
            "abi.svc.email.v1.get_sent", request, pb.GetSentResponse
        )

    async def delete_sent(self, request: pb.DeleteSentRequest) -> pb.DeleteSentResponse:
        return await self._transport.call(
            "abi.svc.email.v1.delete_sent", request, pb.DeleteSentResponse
        )
