# Generated by naas-abi-proto/tools/generate_clients.py; do not edit.
from naas_abi_proto.event.v1 import event_pb2 as pb

from naas_abi_sdk.transport import Transport


class EventClient:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    async def append(self, request: pb.AppendRequest) -> pb.AppendResponse:
        return await self._transport.call(
            "abi.svc.event.v1.append", request, pb.AppendResponse
        )

    async def query(self, request: pb.QueryRequest) -> pb.QueryResponse:
        return await self._transport.call(
            "abi.svc.event.v1.query", request, pb.QueryResponse
        )

    async def max_seq(self, request: pb.MaxSeqRequest) -> pb.MaxSeqResponse:
        return await self._transport.call(
            "abi.svc.event.v1.max_seq", request, pb.MaxSeqResponse
        )

    async def get_cursor(self, request: pb.GetCursorRequest) -> pb.GetCursorResponse:
        return await self._transport.call(
            "abi.svc.event.v1.get_cursor", request, pb.GetCursorResponse
        )

    async def set_cursor(self, request: pb.SetCursorRequest) -> pb.SetCursorResponse:
        return await self._transport.call(
            "abi.svc.event.v1.set_cursor", request, pb.SetCursorResponse
        )

    async def query_for_consumer(
        self, request: pb.QueryForConsumerRequest
    ) -> pb.QueryForConsumerResponse:
        return await self._transport.call(
            "abi.svc.event.v1.query_for_consumer", request, pb.QueryForConsumerResponse
        )
