# Generated by naas-abi-proto/tools/generate_clients.py; do not edit.
from naas_abi_proto.keyvalue.v1 import keyvalue_pb2 as pb

from naas_abi_sdk.transport import Transport


class KeyvalueClient:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    async def get(self, request: pb.GetRequest) -> pb.GetResponse:
        return await self._transport.call(
            "abi.svc.keyvalue.v1.get", request, pb.GetResponse
        )

    async def set(self, request: pb.SetRequest) -> pb.SetResponse:
        return await self._transport.call(
            "abi.svc.keyvalue.v1.set", request, pb.SetResponse
        )

    async def set_if_not_exists(
        self, request: pb.SetIfNotExistsRequest
    ) -> pb.SetIfNotExistsResponse:
        return await self._transport.call(
            "abi.svc.keyvalue.v1.set_if_not_exists", request, pb.SetIfNotExistsResponse
        )

    async def delete(self, request: pb.DeleteRequest) -> pb.DeleteResponse:
        return await self._transport.call(
            "abi.svc.keyvalue.v1.delete", request, pb.DeleteResponse
        )

    async def delete_if_value_matches(
        self, request: pb.DeleteIfValueMatchesRequest
    ) -> pb.DeleteIfValueMatchesResponse:
        return await self._transport.call(
            "abi.svc.keyvalue.v1.delete_if_value_matches",
            request,
            pb.DeleteIfValueMatchesResponse,
        )

    async def exists(self, request: pb.ExistsRequest) -> pb.ExistsResponse:
        return await self._transport.call(
            "abi.svc.keyvalue.v1.exists", request, pb.ExistsResponse
        )
