# Generated by naas-abi-proto/tools/generate_clients.py; do not edit.
from naas_abi_proto.model_registry.v1 import model_registry_pb2 as pb

from naas_abi_sdk.transport import Transport


class ModelRegistryClient:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    async def list_models(self, request: pb.ListModelsRequest) -> pb.ListModelsResponse:
        return await self._transport.call(
            "abi.svc.model_registry.v1.list_models", request, pb.ListModelsResponse
        )

    async def resolve(self, request: pb.ResolveRequest) -> pb.ResolveResponse:
        return await self._transport.call(
            "abi.svc.model_registry.v1.resolve", request, pb.ResolveResponse
        )

    async def chat(self, request: pb.ChatRequest) -> pb.ChatResponse:
        return await self._transport.call(
            "abi.svc.model_registry.v1.chat", request, pb.ChatResponse
        )

    async def stream_open(self, request: pb.StreamOpenRequest) -> pb.StreamOpenResponse:
        return await self._transport.call(
            "abi.svc.model_registry.v1.stream_open", request, pb.StreamOpenResponse
        )

    async def stream_next(self, request: pb.StreamNextRequest) -> pb.StreamNextResponse:
        return await self._transport.call(
            "abi.svc.model_registry.v1.stream_next", request, pb.StreamNextResponse
        )

    async def stream_close(
        self, request: pb.StreamCloseRequest
    ) -> pb.StreamCloseResponse:
        return await self._transport.call(
            "abi.svc.model_registry.v1.stream_close", request, pb.StreamCloseResponse
        )

    async def embed(self, request: pb.EmbedRequest) -> pb.EmbedResponse:
        return await self._transport.call(
            "abi.svc.model_registry.v1.embed", request, pb.EmbedResponse
        )
