# Generated by naas-abi-proto/tools/generate_clients.py; do not edit.
from naas_abi_proto.object_storage.v1 import object_storage_pb2 as pb

from naas_abi_sdk.transport import Transport


class ObjectStorageClient:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    async def get_object(self, request: pb.GetObjectRequest) -> pb.GetObjectResponse:
        return await self._transport.call(
            "abi.svc.object_storage.v1.get_object", request, pb.GetObjectResponse
        )

    async def put_object(self, request: pb.PutObjectRequest) -> pb.PutObjectResponse:
        return await self._transport.call(
            "abi.svc.object_storage.v1.put_object", request, pb.PutObjectResponse
        )

    async def delete_object(
        self, request: pb.DeleteObjectRequest
    ) -> pb.DeleteObjectResponse:
        return await self._transport.call(
            "abi.svc.object_storage.v1.delete_object", request, pb.DeleteObjectResponse
        )

    async def list_objects(
        self, request: pb.ListObjectsRequest
    ) -> pb.ListObjectsResponse:
        return await self._transport.call(
            "abi.svc.object_storage.v1.list_objects", request, pb.ListObjectsResponse
        )

    async def list_objects_recursive(
        self, request: pb.ListObjectsRecursiveRequest
    ) -> pb.ListObjectsRecursiveResponse:
        return await self._transport.call(
            "abi.svc.object_storage.v1.list_objects_recursive",
            request,
            pb.ListObjectsRecursiveResponse,
        )

    async def get_object_metadata(
        self, request: pb.GetObjectMetadataRequest
    ) -> pb.GetObjectMetadataResponse:
        return await self._transport.call(
            "abi.svc.object_storage.v1.get_object_metadata",
            request,
            pb.GetObjectMetadataResponse,
        )
