# Generated by naas-abi-proto/tools/generate_clients.py; do not edit.
from naas_abi_proto.secret.v1 import secret_pb2 as pb

from naas_abi_sdk.transport import Transport


class SecretClient:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    async def get(self, request: pb.GetRequest) -> pb.GetResponse:
        return await self._transport.call(
            "abi.svc.secret.v1.get", request, pb.GetResponse
        )

    async def set(self, request: pb.SetRequest) -> pb.SetResponse:
        return await self._transport.call(
            "abi.svc.secret.v1.set", request, pb.SetResponse
        )

    async def remove(self, request: pb.RemoveRequest) -> pb.RemoveResponse:
        return await self._transport.call(
            "abi.svc.secret.v1.remove", request, pb.RemoveResponse
        )

    async def list(self, request: pb.ListRequest) -> pb.ListResponse:
        return await self._transport.call(
            "abi.svc.secret.v1.list", request, pb.ListResponse
        )
