# Generated by naas-abi-proto/tools/generate_clients.py; do not edit.
from naas_abi_proto.source_control.v1 import source_control_pb2 as pb

from naas_abi_sdk.transport import Transport


class SourceControlClient:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    async def ensure_user(self, request: pb.EnsureUserRequest) -> pb.EnsureUserResponse:
        return await self._transport.call(
            "abi.svc.source_control.v1.ensure_user", request, pb.EnsureUserResponse
        )

    async def ensure_repo(self, request: pb.EnsureRepoRequest) -> pb.EnsureRepoResponse:
        return await self._transport.call(
            "abi.svc.source_control.v1.ensure_repo", request, pb.EnsureRepoResponse
        )

    async def list_repos(self, request: pb.ListReposRequest) -> pb.ListReposResponse:
        return await self._transport.call(
            "abi.svc.source_control.v1.list_repos", request, pb.ListReposResponse
        )

    async def add_collaborator(
        self, request: pb.AddCollaboratorRequest
    ) -> pb.AddCollaboratorResponse:
        return await self._transport.call(
            "abi.svc.source_control.v1.add_collaborator",
            request,
            pb.AddCollaboratorResponse,
        )

    async def list_contents(
        self, request: pb.ListContentsRequest
    ) -> pb.ListContentsResponse:
        return await self._transport.call(
            "abi.svc.source_control.v1.list_contents", request, pb.ListContentsResponse
        )

    async def get_file(self, request: pb.GetFileRequest) -> pb.GetFileResponse:
        return await self._transport.call(
            "abi.svc.source_control.v1.get_file", request, pb.GetFileResponse
        )

    async def upsert_file(self, request: pb.UpsertFileRequest) -> pb.UpsertFileResponse:
        return await self._transport.call(
            "abi.svc.source_control.v1.upsert_file", request, pb.UpsertFileResponse
        )

    async def upsert_files(
        self, request: pb.UpsertFilesRequest
    ) -> pb.UpsertFilesResponse:
        return await self._transport.call(
            "abi.svc.source_control.v1.upsert_files", request, pb.UpsertFilesResponse
        )

    async def list_commits(
        self, request: pb.ListCommitsRequest
    ) -> pb.ListCommitsResponse:
        return await self._transport.call(
            "abi.svc.source_control.v1.list_commits", request, pb.ListCommitsResponse
        )

    async def list_branches(
        self, request: pb.ListBranchesRequest
    ) -> pb.ListBranchesResponse:
        return await self._transport.call(
            "abi.svc.source_control.v1.list_branches", request, pb.ListBranchesResponse
        )

    async def create_branch(
        self, request: pb.CreateBranchRequest
    ) -> pb.CreateBranchResponse:
        return await self._transport.call(
            "abi.svc.source_control.v1.create_branch", request, pb.CreateBranchResponse
        )

    async def delete_branch(
        self, request: pb.DeleteBranchRequest
    ) -> pb.DeleteBranchResponse:
        return await self._transport.call(
            "abi.svc.source_control.v1.delete_branch", request, pb.DeleteBranchResponse
        )

    async def get_diff(self, request: pb.GetDiffRequest) -> pb.GetDiffResponse:
        return await self._transport.call(
            "abi.svc.source_control.v1.get_diff", request, pb.GetDiffResponse
        )

    async def create_proposal(
        self, request: pb.CreateProposalRequest
    ) -> pb.CreateProposalResponse:
        return await self._transport.call(
            "abi.svc.source_control.v1.create_proposal",
            request,
            pb.CreateProposalResponse,
        )

    async def list_proposals(
        self, request: pb.ListProposalsRequest
    ) -> pb.ListProposalsResponse:
        return await self._transport.call(
            "abi.svc.source_control.v1.list_proposals",
            request,
            pb.ListProposalsResponse,
        )

    async def get_proposal(
        self, request: pb.GetProposalRequest
    ) -> pb.GetProposalResponse:
        return await self._transport.call(
            "abi.svc.source_control.v1.get_proposal", request, pb.GetProposalResponse
        )

    async def get_proposal_diff(
        self, request: pb.GetProposalDiffRequest
    ) -> pb.GetProposalDiffResponse:
        return await self._transport.call(
            "abi.svc.source_control.v1.get_proposal_diff",
            request,
            pb.GetProposalDiffResponse,
        )

    async def list_proposal_commits(
        self, request: pb.ListProposalCommitsRequest
    ) -> pb.ListProposalCommitsResponse:
        return await self._transport.call(
            "abi.svc.source_control.v1.list_proposal_commits",
            request,
            pb.ListProposalCommitsResponse,
        )

    async def list_comments(
        self, request: pb.ListCommentsRequest
    ) -> pb.ListCommentsResponse:
        return await self._transport.call(
            "abi.svc.source_control.v1.list_comments", request, pb.ListCommentsResponse
        )

    async def list_reviews(
        self, request: pb.ListReviewsRequest
    ) -> pb.ListReviewsResponse:
        return await self._transport.call(
            "abi.svc.source_control.v1.list_reviews", request, pb.ListReviewsResponse
        )

    async def add_comment(self, request: pb.AddCommentRequest) -> pb.AddCommentResponse:
        return await self._transport.call(
            "abi.svc.source_control.v1.add_comment", request, pb.AddCommentResponse
        )

    async def submit_review(
        self, request: pb.SubmitReviewRequest
    ) -> pb.SubmitReviewResponse:
        return await self._transport.call(
            "abi.svc.source_control.v1.submit_review", request, pb.SubmitReviewResponse
        )

    async def list_checks(self, request: pb.ListChecksRequest) -> pb.ListChecksResponse:
        return await self._transport.call(
            "abi.svc.source_control.v1.list_checks", request, pb.ListChecksResponse
        )

    async def set_branch_protection(
        self, request: pb.SetBranchProtectionRequest
    ) -> pb.SetBranchProtectionResponse:
        return await self._transport.call(
            "abi.svc.source_control.v1.set_branch_protection",
            request,
            pb.SetBranchProtectionResponse,
        )

    async def merge(self, request: pb.MergeRequest) -> pb.MergeResponse:
        return await self._transport.call(
            "abi.svc.source_control.v1.merge", request, pb.MergeResponse
        )

    async def list_workflow_runs(
        self, request: pb.ListWorkflowRunsRequest
    ) -> pb.ListWorkflowRunsResponse:
        return await self._transport.call(
            "abi.svc.source_control.v1.list_workflow_runs",
            request,
            pb.ListWorkflowRunsResponse,
        )

    async def mint_git_token(
        self, request: pb.MintGitTokenRequest
    ) -> pb.MintGitTokenResponse:
        return await self._transport.call(
            "abi.svc.source_control.v1.mint_git_token", request, pb.MintGitTokenResponse
        )
