# Generated by naas-abi-proto/tools/generate_clients.py; do not edit.
from naas_abi_proto.triple_store.v1 import triple_store_pb2 as pb

from naas_abi_sdk.transport import Transport


class TripleStoreClient:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    async def insert(self, request: pb.InsertRequest) -> pb.InsertResponse:
        return await self._transport.call(
            "abi.svc.triple_store.v1.insert", request, pb.InsertResponse
        )

    async def remove(self, request: pb.RemoveRequest) -> pb.RemoveResponse:
        return await self._transport.call(
            "abi.svc.triple_store.v1.remove", request, pb.RemoveResponse
        )

    async def get(self, request: pb.GetRequest) -> pb.GetResponse:
        return await self._transport.call(
            "abi.svc.triple_store.v1.get", request, pb.GetResponse
        )

    async def handle_view_event(
        self, request: pb.HandleViewEventRequest
    ) -> pb.HandleViewEventResponse:
        return await self._transport.call(
            "abi.svc.triple_store.v1.handle_view_event",
            request,
            pb.HandleViewEventResponse,
        )

    async def query(self, request: pb.QueryRequest) -> pb.QueryResponse:
        return await self._transport.call(
            "abi.svc.triple_store.v1.query", request, pb.QueryResponse
        )

    async def query_view(self, request: pb.QueryViewRequest) -> pb.QueryViewResponse:
        return await self._transport.call(
            "abi.svc.triple_store.v1.query_view", request, pb.QueryViewResponse
        )

    async def get_subject_graph(
        self, request: pb.GetSubjectGraphRequest
    ) -> pb.GetSubjectGraphResponse:
        return await self._transport.call(
            "abi.svc.triple_store.v1.get_subject_graph",
            request,
            pb.GetSubjectGraphResponse,
        )

    async def create_graph(
        self, request: pb.CreateGraphRequest
    ) -> pb.CreateGraphResponse:
        return await self._transport.call(
            "abi.svc.triple_store.v1.create_graph", request, pb.CreateGraphResponse
        )

    async def clear_graph(self, request: pb.ClearGraphRequest) -> pb.ClearGraphResponse:
        return await self._transport.call(
            "abi.svc.triple_store.v1.clear_graph", request, pb.ClearGraphResponse
        )

    async def drop_graph(self, request: pb.DropGraphRequest) -> pb.DropGraphResponse:
        return await self._transport.call(
            "abi.svc.triple_store.v1.drop_graph", request, pb.DropGraphResponse
        )

    async def list_graphs(self, request: pb.ListGraphsRequest) -> pb.ListGraphsResponse:
        return await self._transport.call(
            "abi.svc.triple_store.v1.list_graphs", request, pb.ListGraphsResponse
        )
