# Generated by naas-abi-proto/tools/generate_clients.py; do not edit.
from naas_abi_proto.vector_store.v1 import vector_store_pb2 as pb

from naas_abi_sdk.transport import Transport


class VectorStoreClient:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    async def initialize(self, request: pb.InitializeRequest) -> pb.InitializeResponse:
        return await self._transport.call(
            "abi.svc.vector_store.v1.initialize", request, pb.InitializeResponse
        )

    async def create_collection(
        self, request: pb.CreateCollectionRequest
    ) -> pb.CreateCollectionResponse:
        return await self._transport.call(
            "abi.svc.vector_store.v1.create_collection",
            request,
            pb.CreateCollectionResponse,
        )

    async def delete_collection(
        self, request: pb.DeleteCollectionRequest
    ) -> pb.DeleteCollectionResponse:
        return await self._transport.call(
            "abi.svc.vector_store.v1.delete_collection",
            request,
            pb.DeleteCollectionResponse,
        )

    async def list_collections(
        self, request: pb.ListCollectionsRequest
    ) -> pb.ListCollectionsResponse:
        return await self._transport.call(
            "abi.svc.vector_store.v1.list_collections",
            request,
            pb.ListCollectionsResponse,
        )

    async def store_vectors(
        self, request: pb.StoreVectorsRequest
    ) -> pb.StoreVectorsResponse:
        return await self._transport.call(
            "abi.svc.vector_store.v1.store_vectors", request, pb.StoreVectorsResponse
        )

    async def search(self, request: pb.SearchRequest) -> pb.SearchResponse:
        return await self._transport.call(
            "abi.svc.vector_store.v1.search", request, pb.SearchResponse
        )

    async def get_vector(self, request: pb.GetVectorRequest) -> pb.GetVectorResponse:
        return await self._transport.call(
            "abi.svc.vector_store.v1.get_vector", request, pb.GetVectorResponse
        )

    async def update_vector(
        self, request: pb.UpdateVectorRequest
    ) -> pb.UpdateVectorResponse:
        return await self._transport.call(
            "abi.svc.vector_store.v1.update_vector", request, pb.UpdateVectorResponse
        )

    async def delete_vectors(
        self, request: pb.DeleteVectorsRequest
    ) -> pb.DeleteVectorsResponse:
        return await self._transport.call(
            "abi.svc.vector_store.v1.delete_vectors", request, pb.DeleteVectorsResponse
        )

    async def count_vectors(
        self, request: pb.CountVectorsRequest
    ) -> pb.CountVectorsResponse:
        return await self._transport.call(
            "abi.svc.vector_store.v1.count_vectors", request, pb.CountVectorsResponse
        )

    async def close(self, request: pb.CloseRequest) -> pb.CloseResponse:
        return await self._transport.call(
            "abi.svc.vector_store.v1.close", request, pb.CloseResponse
        )
