# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: naas_abi_proto/agent/v1/agent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'naas_abi_proto/agent/v1/agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from naas_abi_proto.common.v1 import common_pb2 as naas__abi__proto_dot_common_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#naas_abi_proto/agent/v1/agent.proto\x12\x0c\x61\x62i.agent.v1\x1a%naas_abi_proto/common/v1/common.proto\";\n\nAgentEvent\x12\x10\n\x08sequence\x18\x01 \x01(\x04\x12\r\n\x05\x65vent\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"\xf6\x01\n\nInvocation\x12\x15\n\rinvocation_id\x18\x01 \x01(\t\x12\x11\n\tthread_id\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x0e\n\x06result\x18\x04 \x01(\t\x12\x12\n\nerror_code\x18\x05 \x01(\t\x12\x15\n\rerror_message\x18\x06 \x01(\t\x12\x19\n\x11owner_instance_id\x18\x07 \x01(\t\x12\x17\n\x0fowner_available\x18\x08 \x01(\x08\x12(\n\x06\x65vents\x18\t \x03(\x0b\x32\x18.abi.agent.v1.AgentEvent\x12\x15\n\rlast_sequence\x18\n \x01(\x04\"\x9e\x01\n\rSubmitRequest\x12+\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x1a.abi.common.v1.CallContext\x12\x15\n\rinvocation_id\x18\x02 \x01(\t\x12\x11\n\tthread_id\x18\x03 \x01(\t\x12\x0e\n\x06prompt\x18\x04 \x01(\t\x12\x0c\n\x04mode\x18\x05 \x01(\t\x12\x18\n\x10\x64\x65\x61\x64line_seconds\x18\x06 \x01(\r\"g\n\x0eSubmitResponse\x12\'\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x18.abi.common.v1.CallError\x12,\n\ninvocation\x18\x02 \x01(\x0b\x32\x18.abi.agent.v1.Invocation\"k\n\rStatusRequest\x12+\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x1a.abi.common.v1.CallContext\x12\x15\n\rinvocation_id\x18\x02 \x01(\t\x12\x16\n\x0e\x61\x66ter_sequence\x18\x03 \x01(\x04\"g\n\x0eStatusResponse\x12\'\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x18.abi.common.v1.CallError\x12,\n\ninvocation\x18\x02 \x01(\x0b\x32\x18.abi.agent.v1.Invocation\"S\n\rCancelRequest\x12+\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x1a.abi.common.v1.CallContext\x12\x15\n\rinvocation_id\x18\x02 \x01(\t\"g\n\x0e\x43\x61ncelResponse\x12\'\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x18.abi.common.v1.CallError\x12,\n\ninvocation\x18\x02 \x01(\x0b\x32\x18.abi.agent.v1.Invocationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'naas_abi_proto.agent.v1.agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGENTEVENT']._serialized_start=92
  _globals['_AGENTEVENT']._serialized_end=151
  _globals['_INVOCATION']._serialized_start=154
  _globals['_INVOCATION']._serialized_end=400
  _globals['_SUBMITREQUEST']._serialized_start=403
  _globals['_SUBMITREQUEST']._serialized_end=561
  _globals['_SUBMITRESPONSE']._serialized_start=563
  _globals['_SUBMITRESPONSE']._serialized_end=666
  _globals['_STATUSREQUEST']._serialized_start=668
  _globals['_STATUSREQUEST']._serialized_end=775
  _globals['_STATUSRESPONSE']._serialized_start=777
  _globals['_STATUSRESPONSE']._serialized_end=880
  _globals['_CANCELREQUEST']._serialized_start=882
  _globals['_CANCELREQUEST']._serialized_end=965
  _globals['_CANCELRESPONSE']._serialized_start=967
  _globals['_CANCELRESPONSE']._serialized_end=1070
# @@protoc_insertion_point(module_scope)
