models:
  - name: "anthropic/claude-3.5-sonnet"
    value: "anthropic.claude-3-5-sonnet-20240620-v1:0"
  
  - name: "anthropic/claude-instant-v1"
    value: "anthropic.claude-instant-v1"
  
  - name: "anthropic/claude-v2.1"
    value: "anthropic.claude-v2:1"
  
  - name: "meta/llama3-70b-instruct-v1"
    value: "meta.llama3-70b-instruct-v1:0"
  
  - name: "meta/llama3-8b-instruct-v1"
    value: "meta.llama3-8b-instruct-v1:0"
  
  - name: "midjourney/imagine-api"
    value: "midjourney/imagine-api"
  
  - name: "mistral/7B-instruct"
    value: "mistral.mistral-7b-instruct-v0:2"
  
  - name: "mistral/8x7B-instruct"
    value: "mistral.mixtral-8x7b-instruct-v0:1"
  
  - name: "mistral/large"
    value: "mistral.mistral-large-2402-v1:0"
  
  - name: "openai/assistant-alpha"
    value: "openai/assistant-alpha"
  
  - name: "openai/gpt-3.5-turbo-16k"
    value: "gpt-3.5-turbo-16k"
  
  - name: "openai/gpt-4"
    value: "gpt-4"
  
  - name: "openai/gpt-4-128k-turbo-preview"
    value: "gpt-4-1106-preview"
  
  - name: "openai/gpt-4o"
    value: "gpt-4o"
  
  - name: "openai/gpt-4o-mini"
    value: "gpt-4o-mini-2024-07-18"
  
  - name: "stabilityai/stable-diffusion-xl"
    value: "stability.stable-diffusion-xl-v1"