base_url = "https://query1.finance.yahoo.com/ws/fundamentals-timeseries/v1/finance/timeseries/AVGO"

params = {
    "merge": "false",
    "padTimeSeries": "true", 
    "period1": "493590046",
    "period2": "1742399999",
    "type": [
        # "quarterlyTaxEffectOfUnusualItems",
        # "trailingTaxEffectOfUnusualItems", 
        # "quarterlyTaxRateForCalcs",
        # "trailingTaxRateForCalcs",
        # "quarterlyNormalizedEBITDA",
        # "trailingNormalizedEBITDA",
        # "quarterlyNormalizedDilutedEPS",
        # "trailingNormalizedDilutedEPS",
        # "quarterlyNormalizedBasicEPS",
        # "trailingNormalizedBasicEPS",
        # "quarterlyTotalUnusualItems",
        # "trailingTotalUnusualItems",
        # "quarterlyTotalUnusualItemsExcludingGoodwill",
        # "trailingTotalUnusualItemsExcludingGoodwill",
        # "quarterlyNetIncomeFromContinuingOperationNetMinorityInterest",
        # "trailingNetIncomeFromContinuingOperationNetMinorityInterest",
        # "quarterlyReconciledDepreciation",
        # "trailingReconciledDepreciation",
        # "quarterlyReconciledCostOfRevenue",
        # "trailingReconciledCostOfRevenue",
        # "quarterlyEBITDA",
        # "trailingEBITDA",
        # "quarterlyEBIT",
        # "trailingEBIT",
        # "quarterlyNetInterestIncome",
        # "trailingNetInterestIncome",
        # "quarterlyInterestExpense",
        # "trailingInterestExpense",
        # "quarterlyInterestIncome",
        # "trailingInterestIncome",
        # "quarterlyContinuingAndDiscontinuedDilutedEPS",
        # "trailingContinuingAndDiscontinuedDilutedEPS",
        # "quarterlyContinuingAndDiscontinuedBasicEPS",
        # "trailingContinuingAndDiscontinuedBasicEPS",
        # "quarterlyNormalizedIncome",
        # "trailingNormalizedIncome",
        # "quarterlyNetIncomeFromContinuingAndDiscontinuedOperation",
        # "trailingNetIncomeFromContinuingAndDiscontinuedOperation",
        # "quarterlyTotalExpenses",
        # "trailingTotalExpenses",
        # "quarterlyRentExpenseSupplemental",
        # "trailingRentExpenseSupplemental",
        # "quarterlyReportedNormalizedDilutedEPS",
        # "trailingReportedNormalizedDilutedEPS",
        # "quarterlyReportedNormalizedBasicEPS",
        # "trailingReportedNormalizedBasicEPS",
        # "quarterlyTotalOperatingIncomeAsReported",
        # "trailingTotalOperatingIncomeAsReported",
        # "quarterlyDividendPerShare",
        # "trailingDividendPerShare",
        # "quarterlyDilutedAverageShares",
        # "trailingDilutedAverageShares",
        # "quarterlyBasicAverageShares",
        # "trailingBasicAverageShares",
        # "quarterlyDilutedEPS",
        # "trailingDilutedEPS",
        # "quarterlyDilutedEPSOtherGainsLosses",
        # "trailingDilutedEPSOtherGainsLosses",
        # "quarterlyTaxLossCarryforwardDilutedEPS",
        # "trailingTaxLossCarryforwardDilutedEPS",
        # "quarterlyDilutedAccountingChange",
        # "trailingDilutedAccountingChange",
        # "quarterlyDilutedExtraordinary",
        # "trailingDilutedExtraordinary",
        # "quarterlyDilutedDiscontinuousOperations",
        # "trailingDilutedDiscontinuousOperations",
        # "quarterlyDilutedContinuousOperations",
        # "trailingDilutedContinuousOperations",
        # "quarterlyBasicEPS",
        # "trailingBasicEPS",
        # "quarterlyBasicEPSOtherGainsLosses",
        # "trailingBasicEPSOtherGainsLosses",
        # "quarterlyTaxLossCarryforwardBasicEPS",
        # "trailingTaxLossCarryforwardBasicEPS",
        # "quarterlyBasicAccountingChange",
        # "trailingBasicAccountingChange",
        # "quarterlyBasicExtraordinary",
        # "trailingBasicExtraordinary",
        # "quarterlyBasicDiscontinuousOperations",
        # "trailingBasicDiscontinuousOperations",
        # "quarterlyBasicContinuousOperations",
        # "trailingBasicContinuousOperations",
        # "quarterlyDilutedNIAvailtoComStockholders",
        # "trailingDilutedNIAvailtoComStockholders",
        # "quarterlyAverageDilutionEarnings",
        # "trailingAverageDilutionEarnings",
        # "quarterlyNetIncomeCommonStockholders",
        # "trailingNetIncomeCommonStockholders",
        # "quarterlyOtherunderPreferredStockDividend",
        # "trailingOtherunderPreferredStockDividend",
        # "quarterlyPreferredStockDividends",
        # "trailingPreferredStockDividends",
        # "quarterlyNetIncome",
        # "trailingNetIncome",
        # "quarterlyMinorityInterests",
        # "trailingMinorityInterests",
        # "quarterlyNetIncomeIncludingNoncontrollingInterests",
        # "trailingNetIncomeIncludingNoncontrollingInterests",
        # "quarterlyNetIncomeFromTaxLossCarryforward",
        # "trailingNetIncomeFromTaxLossCarryforward",
        # "quarterlyNetIncomeExtraordinary",
        # "trailingNetIncomeExtraordinary",
        # "quarterlyNetIncomeDiscontinuousOperations",
        # "trailingNetIncomeDiscontinuousOperations",
        # "quarterlyNetIncomeContinuousOperations",
        # "trailingNetIncomeContinuousOperations",
        # "quarterlyEarningsFromEquityInterestNetOfTax",
        # "trailingEarningsFromEquityInterestNetOfTax",
        # "quarterlyTaxProvision",
        # "trailingTaxProvision",
        # "quarterlyPretaxIncome",
        # "trailingPretaxIncome",
        # "quarterlyOtherIncomeExpense",
        # "trailingOtherIncomeExpense",
        # "quarterlyOtherNonOperatingIncomeExpenses",
        # "trailingOtherNonOperatingIncomeExpenses",
        # "quarterlySpecialIncomeCharges",
        # "trailingSpecialIncomeCharges",
        # "quarterlyGainOnSaleOfPPE",
        # "trailingGainOnSaleOfPPE",
        # "quarterlyGainOnSaleOfBusiness",
        # "trailingGainOnSaleOfBusiness",
        # "quarterlyOtherSpecialCharges",
        # "trailingOtherSpecialCharges",
        # "quarterlyWriteOff",
        # "trailingWriteOff",
        # "quarterlyImpairmentOfCapitalAssets",
        # "trailingImpairmentOfCapitalAssets",
        # "quarterlyRestructuringAndMergernAcquisition",
        # "trailingRestructuringAndMergernAcquisition",
        # "quarterlySecuritiesAmortization",
        # "trailingSecuritiesAmortization",
        # "quarterlyEarningsFromEquityInterest",
        # "trailingEarningsFromEquityInterest",
        # "quarterlyGainOnSaleOfSecurity",
        # "trailingGainOnSaleOfSecurity",
        # "quarterlyNetNonOperatingInterestIncomeExpense",
        # "trailingNetNonOperatingInterestIncomeExpense",
        # "quarterlyTotalOtherFinanceCost",
        # "trailingTotalOtherFinanceCost",
        # "quarterlyInterestExpenseNonOperating",
        # "trailingInterestExpenseNonOperating",
        # "quarterlyInterestIncomeNonOperating",
        # "trailingInterestIncomeNonOperating",
        # "quarterlyOperatingIncome",
        # "trailingOperatingIncome",
        # "quarterlyOperatingExpense",
        # "trailingOperatingExpense",
        # "quarterlyOtherOperatingExpenses",
        # "trailingOtherOperatingExpenses",
        # "quarterlyOtherTaxes",
        # "trailingOtherTaxes",
        # "quarterlyProvisionForDoubtfulAccounts",
        # "trailingProvisionForDoubtfulAccounts",
        # "quarterlyDepreciationAmortizationDepletionIncomeStatement",
        # "trailingDepreciationAmortizationDepletionIncomeStatement",
        # "quarterlyDepletionIncomeStatement",
        # "trailingDepletionIncomeStatement",
        # "quarterlyDepreciationAndAmortizationInIncomeStatement",
        # "trailingDepreciationAndAmortizationInIncomeStatement",
        # "quarterlyAmortization",
        # "trailingAmortization",
        # "quarterlyAmortizationOfIntangiblesIncomeStatement",
        # "trailingAmortizationOfIntangiblesIncomeStatement",
        # "quarterlyDepreciationIncomeStatement",
        # "trailingDepreciationIncomeStatement",
        # "quarterlyResearchAndDevelopment",
        # "trailingResearchAndDevelopment",
        # "quarterlySellingGeneralAndAdministration",
        # "trailingSellingGeneralAndAdministration",
        # "quarterlySellingAndMarketingExpense",
        # "trailingSellingAndMarketingExpense",
        # "quarterlyGeneralAndAdministrativeExpense",
        # "trailingGeneralAndAdministrativeExpense",
        # "quarterlyOtherGandA",
        # "trailingOtherGandA",
        # "quarterlyInsuranceAndClaims",
        # "trailingInsuranceAndClaims",
        # "quarterlyRentAndLandingFees",
        # "trailingRentAndLandingFees",
        # "quarterlySalariesAndWages",
        # "trailingSalariesAndWages",
        # "quarterlyGrossProfit",
        # "trailingGrossProfit",
        # "quarterlyCostOfRevenue",
        # "trailingCostOfRevenue",
        "quarterlyTotalRevenue",
        "trailingTotalRevenue",
        # "quarterlyExciseTaxes",
        # "trailingExciseTaxes",
        "quarterlyOperatingRevenue",
        "trailingOperatingRevenue"
    ],
    "lang": "en-US",
    "region": "US"
}

import requests

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
}

response = requests.get(base_url, params=params, headers=headers)
print(response.json())

# response_json = {
#     "timeseries": {
#         "result": [
#             {
#                 "meta": {
#                     "symbol": ["AVGO"],
#                     "type": ["quarterlyTotalRevenue"]
#                 },
#                 "timestamp": [
#                     1706659200,
#                     1714435200, 
#                     1722384000,
#                     1730332800,
#                     1738281600
#                 ],
#                 "quarterlyTotalRevenue": [
#                     {
#                         "dataId": 20100,
#                         "asOfDate": "2024-01-31",
#                         "periodType": "3M",
#                         "currencyCode": "USD",
#                         "reportedValue": {
#                             "raw": 1.1961E10,
#                             "fmt": "11.96B"
#                         }
#                     },
#                     {
#                         "dataId": 20100,
#                         "asOfDate": "2024-04-30", 
#                         "periodType": "3M",
#                         "currencyCode": "USD",
#                         "reportedValue": {
#                             "raw": 1.2487E10,
#                             "fmt": "12.49B"
#                         }
#                     },
#                     {
#                         "dataId": 20100,
#                         "asOfDate": "2024-07-31",
#                         "periodType": "3M", 
#                         "currencyCode": "USD",
#                         "reportedValue": {
#                             "raw": 1.3072E10,
#                             "fmt": "13.07B"
#                         }
#                     },
#                     {
#                         "dataId": 20100,
#                         "asOfDate": "2024-10-31",
#                         "periodType": "3M",
#                         "currencyCode": "USD", 
#                         "reportedValue": {
#                             "raw": 1.4054E10,
#                             "fmt": "14.05B"
#                         }
#                     },
#                     {
#                         "dataId": 20100,
#                         "asOfDate": "2025-01-31",
#                         "periodType": "3M",
#                         "currencyCode": "USD",
#                         "reportedValue": {
#                             "raw": 1.4916E10,
#                             "fmt": "14.92B"
#                         }
#                     }
#                 ]
#             }
#         ],
#         "error": null
#     }
# }