jobs:
  scheduler:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        username: ${{ github.actor }}
    - name: Pull Docker image
      run: docker pull ghcr.io/${{ github.repository }}/abi:latest
    - name: Execute test/ci.ipynb
      run: 'docker run --name abi-execution -i --platform linux/amd64 ghcr.io/${{
        github.repository }}/abi:latest papermill tests/ci.ipynb outputs/ci.ipynb '
    - name: Run hubspot
      run: 'docker run --name abi-execution -i --platform linux/amd64 ghcr.io/${{
        github.repository }}/abi:latest papermill tests/ci.ipynb outputs/ci.ipynb '
name: Scheduler - main
'on':
  schedule:
  - cron: 0 10 * * *
  workflow_dispatch: {}
