name: Tests and Coverage

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]

    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_USER: abi_user
          POSTGRES_PASSWORD: abi_password
          POSTGRES_DB: abi_memory
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      oxigraph:
        image: oxigraph/oxigraph:latest
        ports:
          - 7878:7878

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install uv package manager
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Install dependencies and setup project
      run: |
        # Install project dependencies
        uv sync --all-extras
        uv add --dev pytest pytest-cov coverage coverage-badge
        
        # Create symbolic link for abi module (matching local setup)
        mkdir -p .venv/lib/python${{ matrix.python-version }}/site-packages/
        ln -sf $PWD/lib/abi .venv/lib/python${{ matrix.python-version }}/site-packages/abi || true
    
    - name: Run unit tests
      env:
        POSTGRES_URL: postgresql://abi_user:abi_password@localhost:5432/abi_memory
        OXIGRAPH_URL: http://localhost:7878
        AI_MODE: test
      run: |
        # Run CI-friendly tests
        make test-ci
    
    - name: Generate coverage badge
      run: |
        uv run coverage-badge -o coverage.svg
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

    - name: Commit coverage badge
      if: github.ref == 'refs/heads/main'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add coverage.svg
        git diff --staged --quiet || git commit -m "Update coverage badge"
        git push || echo "No changes to push"
